#YamlMime:DocDB_Table
id: dbo.Users
title: dbo.Users Table
type: table
created: yyyyMMdd-HHmmssfff
lastModified: yyyyMMdd-HHmmssfff
description: |
    The longish table description.
partitionInfo:
    isPartioned: true
    partitionColumns:
      - XX
      - YY
    partitionScheme: dddd
    fileGroup: xxxx
columns:
  - name: ID
    dataType: INT
    maxLength: 0
    isIdentity: true
    isNullable: false
    isPrimaryKey: true
    isForeignKey: false
    isComputed: false
    default: 
    description: blah blah
indexes:
  - name: IDX_foo
    description: blah
    columns:
    - ID
    - Name
    isUnique: true
    isClustered: false
    isPartitioned: false
triggers:
  - name: MyTrigger
    description: blah blah
    on: ...
foreignKeys:
  - name: FK_ddd
    noCheck: false
    columns:
    - XXX
    - YYY
checks:
  - name: CK_ddd
    on: columnName
    text: dlldld
script: |
    CREATE TABLE .d.d.d.    
    
      