### YamlMime:DocDB
type: TocSection
id: database.adventureworks2022.security
name: Security
databaseId: database.adventureworks2022
lastSchemaModificationAt: 2024-12-17T15:38:40.5330000
schemaVersion: 
description: 
script: 
items:
- id: database.adventureworks2022.security.user
  name: Users
  description: 
- id: database.adventureworks2022.security.schema
  name: Schemas
  description: 
...
