### YamlMime:DocDB
type: TocSection
id: database.adventureworks2022.security.roles.applicationrole
name: Application Roles
databaseId: database.adventureworks2022
lastSchemaModificationAt: 2024-12-17T15:38:40.5330000
schemaVersion: 
description: 
script: 
items:
- id: applicationrole.testapprole
  name: testAppRole
  description: 
...
