### YamlMime:DocDB
type: Table
id: table.sales.countryregioncurrency
description: Cross-reference table mapping ISO currency codes to a country or region.
name: Sales.CountryRegionCurrency
foreignKeys:
- type: ForeignKey
  id: table.sales.countryregioncurrency.foreignkey.fk_countryregioncurrency_countryregion_countryregioncode
  description: Foreign key constraint referencing CountryRegion.CountryRegionCode.
  name: FK_CountryRegionCurrency_CountryRegion_CountryRegionCode
  columns:
  - name: CountryRegionCode
    id: table.sales.countryregioncurrency.column.countryregioncode
    type: TableColumnRef
  isChecked: true
  referencedKey: PK_CountryRegion_CountryRegionCode
  referencedTable:
    name: '[Person].[CountryRegion]'
    id: table.person.countryregion
    type: TableRef
  deleteAction: 
  updateAction: 
  databaseId: database.adventureworks2022
  schemaVersion: 
  lastSchemaModificationAt: 2024-12-17T15:38:40.5330000
  script: ""
- type: ForeignKey
  id: table.sales.countryregioncurrency.foreignkey.fk_countryregioncurrency_currency_currencycode
  description: Foreign key constraint referencing Currency.CurrencyCode.
  name: FK_CountryRegionCurrency_Currency_CurrencyCode
  columns:
  - name: CurrencyCode
    id: table.sales.countryregioncurrency.column.currencycode
    type: TableColumnRef
  isChecked: true
  referencedKey: PK_Currency_CurrencyCode
  referencedTable:
    name: '[Sales].[Currency]'
    id: table.sales.currency
    type: TableRef
  deleteAction: 
  updateAction: 
  databaseId: database.adventureworks2022
  schemaVersion: 
  lastSchemaModificationAt: 2024-12-17T15:38:40.5330000
  script: ""
checks: []
fileGroup:
  name: '[PRIMARY]'
  id: filegroup.primary
  type: FileGroupRef
fileStreamGroup: 
textFileGroup: 
partitionInfo:
  isPartitioned: false
  columns: []
  partitionScheme: 
fileTableInfo:
  isFileTable: false
  directoryName: 
  nameColumnCollation: 
  namespaceEnabled: false
indexes:
- type: Index
  id: table.sales.countryregioncurrency.index.ix_countryregioncurrency_currencycode
  description: Nonclustered index.
  name: IX_CountryRegionCurrency_CurrencyCode
  indexType: NONCLUSTERED
  indexKeyType: ''
  isDisabled: false
  isUnique: false
  isClustered: false
  filter: ''
  columns:
  - type: IndexColumn
    id: table.sales.countryregioncurrency.index.ix_countryregioncurrency_currencycode.indexedcolumn.currencycode
    description: 
    name: CurrencyCode
    columnRef:
      name: CurrencyCode
      id: table.sales.countryregioncurrency.column.currencycode
      type: TableColumnRef
    isDescending: false
    isIncluded: false
    columnStoreOrderOrdinal: 0
    databaseId: database.adventureworks2022
    schemaVersion: 
    lastSchemaModificationAt: 2024-12-17T15:38:40.5330000
    script: ""
  partitionInfo:
    isPartitioned: false
    columns: []
    partitionScheme: 
  fileGroup:
    name: PRIMARY
    id: filegroup.primary
    type: FileGroupRef
  fileStreamGroup: 
  options:
  - name: general
    entries:
    - name: autoRecomputeStatistics
      value: true
      type: bool
    - name: ignoreDuplicateKeys
      value: false
      type: bool
  - name: storage
    entries:
    - name: sortInTempdb
      value: 
      type: 
    - name: fillFactor
      value: 0
      type: string
    - name: padIndex
      value: false
      type: bool
  - name: operation
    entries:
    - name: maximumDegreeOfParallelism
      value: 
      type: 
    - name: isOptimizedForSequentialKey
      value: false
      type: bool
  - name: locks
    entries:
    - name: allowPageLocks
      value: true
      type: bool
    - name: allowRowLocks
      value: true
      type: bool
  - name: spatial
    entries:
    - name: isSpatialIndex
      value: false
      type: bool
  - name: xml
    entries:
    - name: isXmlIndex
      value: false
      type: bool
  - name: miscellaneous
    entries:
    - name: hasCompressedPartitions
      value: false
      type: bool
    - name: hasXmlCompressedPartitions
      value: false
      type: bool
    - name: compressAllRowGroups
      value: 
      type: 
    - name: compactLargeObjects
      value: 
      type: 
    - name: compressionDelay
      value: 
      type: 
    - name: dropExistingIndex
      value: 
      type: 
    - name: hasSparseColumn
      value: false
      type: bool
    - name: isFileTableDefined
      value: false
      type: bool
    - name: isFullTextKey
      value: false
      type: bool
    - name: isIndexOnComputed
      value: 
      type: 
    - name: isIndexOnTable
      value: 
      type: 
    - name: isMemoryOptimized
      value: false
      type: bool
    - name: isOnlineRebuildSupported
      value: 
      type: 
    - name: isOptimizedForSequentialKey
      value: false
      type: bool
    - name: lowPriorityAbortAfterWait
      value: 
      type: 
    - name: lowPriorityMaxDuration
      value: 
      type: 
    - name: lowPriorityMaxDuration
      value: 
      type: 
    - name: onlineIndexOperation
      value: 
      type: 
    - name: resumableIndexOperation
      value: 
      type: 
    - name: resumableMaxDuration
      value: 
      type: 
    - name: resumableOperationState
      value: None
      type: enum
  databaseId: database.adventureworks2022
  schemaVersion: 
  lastSchemaModificationAt: 2024-12-17T15:38:40.5330000
  script: ""
- type: Index
  id: table.sales.countryregioncurrency.index.pk_countryregioncurrency_countryregioncode_currencycode
  description: Primary key (clustered) constraint
  name: PK_CountryRegionCurrency_CountryRegionCode_CurrencyCode
  indexType: CLUSTERED
  indexKeyType: PRIMARY
  isDisabled: false
  isUnique: true
  isClustered: true
  filter: ''
  columns:
  - type: IndexColumn
    id: table.sales.countryregioncurrency.index.pk_countryregioncurrency_countryregioncode_currencycode.indexedcolumn.countryregioncode
    description: 
    name: CountryRegionCode
    columnRef:
      name: CountryRegionCode
      id: table.sales.countryregioncurrency.column.countryregioncode
      type: TableColumnRef
    isDescending: false
    isIncluded: false
    columnStoreOrderOrdinal: 0
    databaseId: database.adventureworks2022
    schemaVersion: 
    lastSchemaModificationAt: 2024-12-17T15:38:40.5330000
    script: ""
  - type: IndexColumn
    id: table.sales.countryregioncurrency.index.pk_countryregioncurrency_countryregioncode_currencycode.indexedcolumn.currencycode
    description: 
    name: CurrencyCode
    columnRef:
      name: CurrencyCode
      id: table.sales.countryregioncurrency.column.currencycode
      type: TableColumnRef
    isDescending: false
    isIncluded: false
    columnStoreOrderOrdinal: 0
    databaseId: database.adventureworks2022
    schemaVersion: 
    lastSchemaModificationAt: 2024-12-17T15:38:40.5330000
    script: ""
  partitionInfo:
    isPartitioned: false
    columns: []
    partitionScheme: 
  fileGroup:
    name: PRIMARY
    id: filegroup.primary
    type: FileGroupRef
  fileStreamGroup: 
  options:
  - name: general
    entries:
    - name: autoRecomputeStatistics
      value: true
      type: bool
    - name: ignoreDuplicateKeys
      value: false
      type: bool
  - name: storage
    entries:
    - name: sortInTempdb
      value: 
      type: 
    - name: fillFactor
      value: 0
      type: string
    - name: padIndex
      value: false
      type: bool
  - name: operation
    entries:
    - name: maximumDegreeOfParallelism
      value: 
      type: 
    - name: isOptimizedForSequentialKey
      value: false
      type: bool
  - name: locks
    entries:
    - name: allowPageLocks
      value: true
      type: bool
    - name: allowRowLocks
      value: true
      type: bool
  - name: spatial
    entries:
    - name: isSpatialIndex
      value: false
      type: bool
  - name: xml
    entries:
    - name: isXmlIndex
      value: false
      type: bool
  - name: miscellaneous
    entries:
    - name: hasCompressedPartitions
      value: false
      type: bool
    - name: hasXmlCompressedPartitions
      value: false
      type: bool
    - name: compressAllRowGroups
      value: 
      type: 
    - name: compactLargeObjects
      value: 
      type: 
    - name: compressionDelay
      value: 
      type: 
    - name: dropExistingIndex
      value: 
      type: 
    - name: hasSparseColumn
      value: false
      type: bool
    - name: isFileTableDefined
      value: false
      type: bool
    - name: isFullTextKey
      value: false
      type: bool
    - name: isIndexOnComputed
      value: 
      type: 
    - name: isIndexOnTable
      value: 
      type: 
    - name: isMemoryOptimized
      value: false
      type: bool
    - name: isOnlineRebuildSupported
      value: 
      type: 
    - name: isOptimizedForSequentialKey
      value: false
      type: bool
    - name: lowPriorityAbortAfterWait
      value: 
      type: 
    - name: lowPriorityMaxDuration
      value: 
      type: 
    - name: lowPriorityMaxDuration
      value: 
      type: 
    - name: onlineIndexOperation
      value: 
      type: 
    - name: resumableIndexOperation
      value: 
      type: 
    - name: resumableMaxDuration
      value: 
      type: 
    - name: resumableOperationState
      value: None
      type: enum
  databaseId: database.adventureworks2022
  schemaVersion: 
  lastSchemaModificationAt: 2024-12-17T15:38:40.5330000
  script: ""
triggers: []
columns:
- type: TableColumn
  id: table.sales.countryregioncurrency.column.countryregioncode
  description: ISO code for countries and regions. Foreign key to CountryRegion.CountryRegionCode.
  name: CountryRegionCode
  dataType: NVARCHAR(3)
  dataTypeRef: 
  maxLengthBytes: 3
  precision: 0
  scale: 0
  isNullable: false
  isComputed: false
  computedText: ''
  isIdentity: false
  identityIncrement: 0
  identitySeed: 0
  inPrimaryKey: true
  isForeignKey: true
  foreignKeys:
  - name: FK_CountryRegionCurrency_CountryRegion_CountryRegionCode
    id: table.sales.countryregioncurrency.foreignkey.fk_countryregioncurrency_countryregion_countryregioncode
    type: ForeignKeyRef
  default: 
  collation: SQL_Latin1_General_CP1_CI_AS
  isFileStream: false
  isFullTextIndexed: false
  databaseId: database.adventureworks2022
  schemaVersion: 
  lastSchemaModificationAt: 2024-12-17T15:38:40.5330000
  script: ""
- type: TableColumn
  id: table.sales.countryregioncurrency.column.currencycode
  description: ISO standard currency code. Foreign key to Currency.CurrencyCode.
  name: CurrencyCode
  dataType: NCHAR(3)
  dataTypeRef: 
  maxLengthBytes: 3
  precision: 0
  scale: 0
  isNullable: false
  isComputed: false
  computedText: ''
  isIdentity: false
  identityIncrement: 0
  identitySeed: 0
  inPrimaryKey: true
  isForeignKey: true
  foreignKeys:
  - name: FK_CountryRegionCurrency_Currency_CurrencyCode
    id: table.sales.countryregioncurrency.foreignkey.fk_countryregioncurrency_currency_currencycode
    type: ForeignKeyRef
  default: 
  collation: SQL_Latin1_General_CP1_CI_AS
  isFileStream: false
  isFullTextIndexed: false
  databaseId: database.adventureworks2022
  schemaVersion: 
  lastSchemaModificationAt: 2024-12-17T15:38:40.5330000
  script: ""
- type: TableColumn
  id: table.sales.countryregioncurrency.column.modifieddate
  description: Date and time the record was last updated.
  name: ModifiedDate
  dataType: DATETIME
  dataTypeRef: 
  maxLengthBytes: 8
  precision: 23
  scale: 3
  isNullable: false
  isComputed: false
  computedText: ''
  isIdentity: false
  identityIncrement: 0
  identitySeed: 0
  inPrimaryKey: false
  isForeignKey: false
  foreignKeys: []
  default: (getdate())
  collation: ''
  isFileStream: false
  isFullTextIndexed: false
  databaseId: database.adventureworks2022
  schemaVersion: 
  lastSchemaModificationAt: 2024-12-17T15:38:40.5330000
  script: ""
databaseId: database.adventureworks2022
schemaVersion: 
lastSchemaModificationAt: 2024-12-17T15:38:40.5330000
script: |+
  SET ANSI_NULLS ON
  GO

  SET QUOTED_IDENTIFIER ON
  GO

  CREATE TABLE [Sales].[CountryRegionCurrency](
  	[CountryRegionCode] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
  	[CurrencyCode] [nchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
  	[ModifiedDate] [datetime] NOT NULL,
   CONSTRAINT [PK_CountryRegionCurrency_CountryRegionCode_CurrencyCode] PRIMARY KEY CLUSTERED
  (
  	[CountryRegionCode] ASC,
  	[CurrencyCode] ASC
  )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
  ) ON [PRIMARY]

  GO

  SET ANSI_PADDING ON
  GO

  CREATE NONCLUSTERED INDEX [IX_CountryRegionCurrency_CurrencyCode] ON [Sales].[CountryRegionCurrency]
  (
  	[CurrencyCode] ASC
  )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
  GO

  ALTER TABLE [Sales].[CountryRegionCurrency] ADD  CONSTRAINT [DF_CountryRegionCurrency_ModifiedDate]  DEFAULT (getdate()) FOR [ModifiedDate]
  GO

  ALTER TABLE [Sales].[CountryRegionCurrency]  WITH CHECK ADD  CONSTRAINT [FK_CountryRegionCurrency_CountryRegion_CountryRegionCode] FOREIGN KEY([CountryRegionCode])
  REFERENCES [Person].[CountryRegion] ([CountryRegionCode])
  GO

  ALTER TABLE [Sales].[CountryRegionCurrency] CHECK CONSTRAINT [FK_CountryRegionCurrency_CountryRegion_CountryRegionCode]
  GO

  ALTER TABLE [Sales].[CountryRegionCurrency]  WITH CHECK ADD  CONSTRAINT [FK_CountryRegionCurrency_Currency_CurrencyCode] FOREIGN KEY([CurrencyCode])
  REFERENCES [Sales].[Currency] ([CurrencyCode])
  GO

  ALTER TABLE [Sales].[CountryRegionCurrency] CHECK CONSTRAINT [FK_CountryRegionCurrency_Currency_CurrencyCode]
  GO

