### YamlMime:DocDB
type: View
id: view.sales.vstorewithaddresses
description: Stores (including store addresses) that sell Adventure Works Cycles products to consumers.
name: Sales.vStoreWithAddresses
indexes: []
triggers: []
columns:
- type: ViewColumn
  id: view.sales.vstorewithaddresses.column.businessentityid
  description: 
  name: BusinessEntityID
  dataType: INT
  dataTypeRef: 
  maxLengthBytes: 4
  precision: 10
  scale: 0
  isNullable: false
  isComputed: false
  computedText: ''
  isIdentity: false
  identityIncrement: 0
  identitySeed: 0
  inPrimaryKey: false
  isForeignKey: false
  foreignKeys: []
  default: 
  collation: ''
  isFileStream: false
  isFullTextIndexed: false
  databaseId: database.adventureworks2022
  schemaVersion: 
  lastSchemaModificationAt: 2024-12-17T15:38:40.5330000
  script: ""
- type: ViewColumn
  id: view.sales.vstorewithaddresses.column.name
  description: 
  name: Name
  dataType: '[dbo].[Name]'
  dataTypeRef:
    name: '[dbo].[Name]'
    id: userdefineddatatype.dbo.name
    type: UserDefinedDataTypeRef
  maxLengthBytes: 50
  precision: 0
  scale: 0
  isNullable: false
  isComputed: false
  computedText: ''
  isIdentity: false
  identityIncrement: 0
  identitySeed: 0
  inPrimaryKey: false
  isForeignKey: false
  foreignKeys: []
  default: 
  collation: SQL_Latin1_General_CP1_CI_AS
  isFileStream: false
  isFullTextIndexed: false
  databaseId: database.adventureworks2022
  schemaVersion: 
  lastSchemaModificationAt: 2024-12-17T15:38:40.5330000
  script: ""
- type: ViewColumn
  id: view.sales.vstorewithaddresses.column.addresstype
  description: 
  name: AddressType
  dataType: '[dbo].[Name]'
  dataTypeRef:
    name: '[dbo].[Name]'
    id: userdefineddatatype.dbo.name
    type: UserDefinedDataTypeRef
  maxLengthBytes: 50
  precision: 0
  scale: 0
  isNullable: false
  isComputed: false
  computedText: ''
  isIdentity: false
  identityIncrement: 0
  identitySeed: 0
  inPrimaryKey: false
  isForeignKey: false
  foreignKeys: []
  default: 
  collation: SQL_Latin1_General_CP1_CI_AS
  isFileStream: false
  isFullTextIndexed: false
  databaseId: database.adventureworks2022
  schemaVersion: 
  lastSchemaModificationAt: 2024-12-17T15:38:40.5330000
  script: ""
- type: ViewColumn
  id: view.sales.vstorewithaddresses.column.addressline1
  description: 
  name: AddressLine1
  dataType: NVARCHAR(60)
  dataTypeRef: 
  maxLengthBytes: 60
  precision: 0
  scale: 0
  isNullable: false
  isComputed: false
  computedText: ''
  isIdentity: false
  identityIncrement: 0
  identitySeed: 0
  inPrimaryKey: false
  isForeignKey: false
  foreignKeys: []
  default: 
  collation: SQL_Latin1_General_CP1_CI_AS
  isFileStream: false
  isFullTextIndexed: false
  databaseId: database.adventureworks2022
  schemaVersion: 
  lastSchemaModificationAt: 2024-12-17T15:38:40.5330000
  script: ""
- type: ViewColumn
  id: view.sales.vstorewithaddresses.column.addressline2
  description: 
  name: AddressLine2
  dataType: NVARCHAR(60)
  dataTypeRef: 
  maxLengthBytes: 60
  precision: 0
  scale: 0
  isNullable: true
  isComputed: false
  computedText: ''
  isIdentity: false
  identityIncrement: 0
  identitySeed: 0
  inPrimaryKey: false
  isForeignKey: false
  foreignKeys: []
  default: 
  collation: SQL_Latin1_General_CP1_CI_AS
  isFileStream: false
  isFullTextIndexed: false
  databaseId: database.adventureworks2022
  schemaVersion: 
  lastSchemaModificationAt: 2024-12-17T15:38:40.5330000
  script: ""
- type: ViewColumn
  id: view.sales.vstorewithaddresses.column.city
  description: 
  name: City
  dataType: NVARCHAR(30)
  dataTypeRef: 
  maxLengthBytes: 30
  precision: 0
  scale: 0
  isNullable: false
  isComputed: false
  computedText: ''
  isIdentity: false
  identityIncrement: 0
  identitySeed: 0
  inPrimaryKey: false
  isForeignKey: false
  foreignKeys: []
  default: 
  collation: SQL_Latin1_General_CP1_CI_AS
  isFileStream: false
  isFullTextIndexed: false
  databaseId: database.adventureworks2022
  schemaVersion: 
  lastSchemaModificationAt: 2024-12-17T15:38:40.5330000
  script: ""
- type: ViewColumn
  id: view.sales.vstorewithaddresses.column.stateprovincename
  description: 
  name: StateProvinceName
  dataType: '[dbo].[Name]'
  dataTypeRef:
    name: '[dbo].[Name]'
    id: userdefineddatatype.dbo.name
    type: UserDefinedDataTypeRef
  maxLengthBytes: 50
  precision: 0
  scale: 0
  isNullable: false
  isComputed: false
  computedText: ''
  isIdentity: false
  identityIncrement: 0
  identitySeed: 0
  inPrimaryKey: false
  isForeignKey: false
  foreignKeys: []
  default: 
  collation: SQL_Latin1_General_CP1_CI_AS
  isFileStream: false
  isFullTextIndexed: false
  databaseId: database.adventureworks2022
  schemaVersion: 
  lastSchemaModificationAt: 2024-12-17T15:38:40.5330000
  script: ""
- type: ViewColumn
  id: view.sales.vstorewithaddresses.column.postalcode
  description: 
  name: PostalCode
  dataType: NVARCHAR(15)
  dataTypeRef: 
  maxLengthBytes: 15
  precision: 0
  scale: 0
  isNullable: false
  isComputed: false
  computedText: ''
  isIdentity: false
  identityIncrement: 0
  identitySeed: 0
  inPrimaryKey: false
  isForeignKey: false
  foreignKeys: []
  default: 
  collation: SQL_Latin1_General_CP1_CI_AS
  isFileStream: false
  isFullTextIndexed: false
  databaseId: database.adventureworks2022
  schemaVersion: 
  lastSchemaModificationAt: 2024-12-17T15:38:40.5330000
  script: ""
- type: ViewColumn
  id: view.sales.vstorewithaddresses.column.countryregionname
  description: 
  name: CountryRegionName
  dataType: '[dbo].[Name]'
  dataTypeRef:
    name: '[dbo].[Name]'
    id: userdefineddatatype.dbo.name
    type: UserDefinedDataTypeRef
  maxLengthBytes: 50
  precision: 0
  scale: 0
  isNullable: false
  isComputed: false
  computedText: ''
  isIdentity: false
  identityIncrement: 0
  identitySeed: 0
  inPrimaryKey: false
  isForeignKey: false
  foreignKeys: []
  default: 
  collation: SQL_Latin1_General_CP1_CI_AS
  isFileStream: false
  isFullTextIndexed: false
  databaseId: database.adventureworks2022
  schemaVersion: 
  lastSchemaModificationAt: 2024-12-17T15:38:40.5330000
  script: ""
databaseId: database.adventureworks2022
schemaVersion: 
lastSchemaModificationAt: 2024-12-17T15:38:40.5330000
script: |+
  SET ANSI_NULLS ON
  GO

  SET QUOTED_IDENTIFIER ON
  GO

  CREATE VIEW [Sales].[vStoreWithAddresses] AS
  SELECT
      s.[BusinessEntityID]
      ,s.[Name]
      ,at.[Name] AS [AddressType]
      ,a.[AddressLine1]
      ,a.[AddressLine2]
      ,a.[City]
      ,sp.[Name] AS [StateProvinceName]
      ,a.[PostalCode]
      ,cr.[Name] AS [CountryRegionName]
  FROM [Sales].[Store] s
      INNER JOIN [Person].[BusinessEntityAddress] bea
      ON bea.[BusinessEntityID] = s.[BusinessEntityID]
      INNER JOIN [Person].[Address] a
      ON a.[AddressID] = bea.[AddressID]
      INNER JOIN [Person].[StateProvince] sp
      ON sp.[StateProvinceID] = a.[StateProvinceID]
      INNER JOIN [Person].[CountryRegion] cr
      ON cr.[CountryRegionCode] = sp.[CountryRegionCode]
      INNER JOIN [Person].[AddressType] at
      ON at.[AddressTypeID] = bea.[AddressTypeID];

  GO

