### YamlMime:DocDB
type: View
id: view.sales.vsalespersonsalesbyfiscalyears
description: Uses PIVOT to return aggregated sales information for each sales representative.
name: Sales.vSalesPersonSalesByFiscalYears
indexes: []
triggers: []
columns:
- type: ViewColumn
  id: view.sales.vsalespersonsalesbyfiscalyears.column.salespersonid
  description: 
  name: SalesPersonID
  dataType: INT
  dataTypeRef: 
  maxLengthBytes: 4
  precision: 10
  scale: 0
  isNullable: true
  isComputed: false
  computedText: ''
  isIdentity: false
  identityIncrement: 0
  identitySeed: 0
  inPrimaryKey: false
  isForeignKey: false
  foreignKeys: []
  default: 
  collation: ''
  isFileStream: false
  isFullTextIndexed: false
  databaseId: database.adventureworks2022
  schemaVersion: 
  lastSchemaModificationAt: 2024-12-17T15:38:40.5330000
  script: ""
- type: ViewColumn
  id: view.sales.vsalespersonsalesbyfiscalyears.column.fullname
  description: 
  name: FullName
  dataType: NVARCHAR(152)
  dataTypeRef: 
  maxLengthBytes: 152
  precision: 0
  scale: 0
  isNullable: true
  isComputed: false
  computedText: ''
  isIdentity: false
  identityIncrement: 0
  identitySeed: 0
  inPrimaryKey: false
  isForeignKey: false
  foreignKeys: []
  default: 
  collation: SQL_Latin1_General_CP1_CI_AS
  isFileStream: false
  isFullTextIndexed: false
  databaseId: database.adventureworks2022
  schemaVersion: 
  lastSchemaModificationAt: 2024-12-17T15:38:40.5330000
  script: ""
- type: ViewColumn
  id: view.sales.vsalespersonsalesbyfiscalyears.column.jobtitle
  description: 
  name: JobTitle
  dataType: NVARCHAR(50)
  dataTypeRef: 
  maxLengthBytes: 50
  precision: 0
  scale: 0
  isNullable: false
  isComputed: false
  computedText: ''
  isIdentity: false
  identityIncrement: 0
  identitySeed: 0
  inPrimaryKey: false
  isForeignKey: false
  foreignKeys: []
  default: 
  collation: SQL_Latin1_General_CP1_CI_AS
  isFileStream: false
  isFullTextIndexed: false
  databaseId: database.adventureworks2022
  schemaVersion: 
  lastSchemaModificationAt: 2024-12-17T15:38:40.5330000
  script: ""
- type: ViewColumn
  id: view.sales.vsalespersonsalesbyfiscalyears.column.salesterritory
  description: 
  name: SalesTerritory
  dataType: '[dbo].[Name]'
  dataTypeRef:
    name: '[dbo].[Name]'
    id: userdefineddatatype.dbo.name
    type: UserDefinedDataTypeRef
  maxLengthBytes: 50
  precision: 0
  scale: 0
  isNullable: false
  isComputed: false
  computedText: ''
  isIdentity: false
  identityIncrement: 0
  identitySeed: 0
  inPrimaryKey: false
  isForeignKey: false
  foreignKeys: []
  default: 
  collation: SQL_Latin1_General_CP1_CI_AS
  isFileStream: false
  isFullTextIndexed: false
  databaseId: database.adventureworks2022
  schemaVersion: 
  lastSchemaModificationAt: 2024-12-17T15:38:40.5330000
  script: ""
- type: ViewColumn
  id: view.sales.vsalespersonsalesbyfiscalyears.column.2002
  description: 
  name: 2002
  dataType: MONEY
  dataTypeRef: 
  maxLengthBytes: 8
  precision: 19
  scale: 4
  isNullable: true
  isComputed: false
  computedText: ''
  isIdentity: false
  identityIncrement: 0
  identitySeed: 0
  inPrimaryKey: false
  isForeignKey: false
  foreignKeys: []
  default: 
  collation: ''
  isFileStream: false
  isFullTextIndexed: false
  databaseId: database.adventureworks2022
  schemaVersion: 
  lastSchemaModificationAt: 2024-12-17T15:38:40.5330000
  script: ""
- type: ViewColumn
  id: view.sales.vsalespersonsalesbyfiscalyears.column.2003
  description: 
  name: 2003
  dataType: MONEY
  dataTypeRef: 
  maxLengthBytes: 8
  precision: 19
  scale: 4
  isNullable: true
  isComputed: false
  computedText: ''
  isIdentity: false
  identityIncrement: 0
  identitySeed: 0
  inPrimaryKey: false
  isForeignKey: false
  foreignKeys: []
  default: 
  collation: ''
  isFileStream: false
  isFullTextIndexed: false
  databaseId: database.adventureworks2022
  schemaVersion: 
  lastSchemaModificationAt: 2024-12-17T15:38:40.5330000
  script: ""
- type: ViewColumn
  id: view.sales.vsalespersonsalesbyfiscalyears.column.2004
  description: 
  name: 2004
  dataType: MONEY
  dataTypeRef: 
  maxLengthBytes: 8
  precision: 19
  scale: 4
  isNullable: true
  isComputed: false
  computedText: ''
  isIdentity: false
  identityIncrement: 0
  identitySeed: 0
  inPrimaryKey: false
  isForeignKey: false
  foreignKeys: []
  default: 
  collation: ''
  isFileStream: false
  isFullTextIndexed: false
  databaseId: database.adventureworks2022
  schemaVersion: 
  lastSchemaModificationAt: 2024-12-17T15:38:40.5330000
  script: ""
databaseId: database.adventureworks2022
schemaVersion: 
lastSchemaModificationAt: 2024-12-17T15:38:40.5330000
script: |+
  SET ANSI_NULLS ON
  GO

  SET QUOTED_IDENTIFIER ON
  GO

  CREATE VIEW [Sales].[vSalesPersonSalesByFiscalYears]
  AS
  SELECT
      pvt.[SalesPersonID]
      ,pvt.[FullName]
      ,pvt.[JobTitle]
      ,pvt.[SalesTerritory]
      ,pvt.[2002]
      ,pvt.[2003]
      ,pvt.[2004]
  FROM (SELECT
          soh.[SalesPersonID]
          ,p.[FirstName] + ' ' + COALESCE(p.[MiddleName], '') + ' ' + p.[LastName] AS [FullName]
          ,e.[JobTitle]
          ,st.[Name] AS [SalesTerritory]
          ,soh.[SubTotal]
          ,YEAR(DATEADD(m, 6, soh.[OrderDate])) AS [FiscalYear]
      FROM [Sales].[SalesPerson] sp
          INNER JOIN [Sales].[SalesOrderHeader] soh
          ON sp.[BusinessEntityID] = soh.[SalesPersonID]
          INNER JOIN [Sales].[SalesTerritory] st
          ON sp.[TerritoryID] = st.[TerritoryID]
          INNER JOIN [HumanResources].[Employee] e
          ON soh.[SalesPersonID] = e.[BusinessEntityID]
  		INNER JOIN [Person].[Person] p
  		ON p.[BusinessEntityID] = sp.[BusinessEntityID]
  	 ) AS soh
  PIVOT
  (
      SUM([SubTotal])
      FOR [FiscalYear]
      IN ([2002], [2003], [2004])
  ) AS pvt;

  GO

