### YamlMime:DocDB
type: TocSection
id: database.adventureworks2022.security.roles.applicationrole
name: Application Roles
databaseId: database.adventureworks2022
lastSchemaModificationAt: 2024-12-16T15:41:06.5500000
schemaVersion: 
description: 
script: 
items:
- id: applicationrole.testapprole
  name: testAppRole
  description: 
...
