### YamlMime:DocDB
type: Table
id: table.sales.personcreditcard
description: 'Cross-reference table mapping people to their credit card information in the CreditCard table. '
name: Sales.PersonCreditCard
foreignKeys:
- type: ForeignKey
  id: table.sales.personcreditcard.foreignkey.fk_personcreditcard_creditcard_creditcardid
  description: Foreign key constraint referencing CreditCard.CreditCardID.
  name: FK_PersonCreditCard_CreditCard_CreditCardID
  columns:
  - name: CreditCardID
    id: table.sales.personcreditcard.column.creditcardid
    type: TableColumnRef
  isChecked: true
  referencedKey: PK_CreditCard_CreditCardID
  referencedTable:
    name: '[Sales].[CreditCard]'
    id: table.sales.creditcard
    type: TableRef
  deleteAction: 
  updateAction: 
  databaseId: database.adventureworks2022
  script: ""
- type: ForeignKey
  id: table.sales.personcreditcard.foreignkey.fk_personcreditcard_person_businessentityid
  description: Foreign key constraint referencing Person.BusinessEntityID.
  name: FK_PersonCreditCard_Person_BusinessEntityID
  columns:
  - name: BusinessEntityID
    id: table.sales.personcreditcard.column.businessentityid
    type: TableColumnRef
  isChecked: true
  referencedKey: PK_Person_BusinessEntityID
  referencedTable:
    name: '[Person].[Person]'
    id: table.person.person
    type: TableRef
  deleteAction: 
  updateAction: 
  databaseId: database.adventureworks2022
  script: ""
checks: []
fileGroup:
  name: '[PRIMARY]'
  id: filegroup.primary
  type: FileGroupRef
fileStreamGroup: 
textFileGroup: 
partitionInfo:
  isPartitioned: false
  columns: []
  partitionScheme: 
fileTableInfo:
  isFileTable: false
  directoryName: 
  nameColumnCollation: 
  namespaceEnabled: false
indexes:
- type: Index
  id: table.sales.personcreditcard.index.pk_personcreditcard_businessentityid_creditcardid
  description: Primary key (clustered) constraint
  name: PK_PersonCreditCard_BusinessEntityID_CreditCardID
  indexType: CLUSTERED
  indexKeyType: PRIMARY
  isDisabled: false
  isUnique: true
  isClustered: true
  filter: ''
  columns:
  - type: IndexColumn
    id: table.sales.personcreditcard.index.pk_personcreditcard_businessentityid_creditcardid.indexedcolumn.businessentityid
    description: 
    name: BusinessEntityID
    columnRef:
      name: BusinessEntityID
      id: table.sales.personcreditcard.column.businessentityid
      type: TableColumnRef
    isDescending: false
    isIncluded: false
    columnStoreOrderOrdinal: 0
    databaseId: database.adventureworks2022
    script: ""
  - type: IndexColumn
    id: table.sales.personcreditcard.index.pk_personcreditcard_businessentityid_creditcardid.indexedcolumn.creditcardid
    description: 
    name: CreditCardID
    columnRef:
      name: CreditCardID
      id: table.sales.personcreditcard.column.creditcardid
      type: TableColumnRef
    isDescending: false
    isIncluded: false
    columnStoreOrderOrdinal: 0
    databaseId: database.adventureworks2022
    script: ""
  isPartitioned: false
  fileGroup:
    name: PRIMARY
    id: filegroup.primary
    type: FileGroupRef
  fileStreamGroup: 
  options:
  - name: general
    entries:
    - name: autoRecomputeStatistics
      value: true
      type: bool
    - name: ignoreDuplicateKeys
      value: false
      type: bool
  - name: storage
    entries:
    - name: sortInTempdb
      value: 
      type: 
    - name: fillFactor
      value: 0
      type: string
    - name: padIndex
      value: false
      type: bool
  - name: operation
    entries:
    - name: maximumDegreeOfParallelism
      value: 
      type: 
    - name: isOptimizedForSequentialKey
      value: false
      type: bool
  - name: locks
    entries:
    - name: allowPageLocks
      value: true
      type: bool
    - name: allowRowLocks
      value: true
      type: bool
  - name: spatial
    entries:
    - name: isSpatialIndex
      value: false
      type: bool
  - name: xml
    entries:
    - name: isXmlIndex
      value: false
      type: bool
  - name: miscellaneous
    entries:
    - name: hasCompressedPartitions
      value: false
      type: bool
    - name: hasXmlCompressedPartitions
      value: false
      type: bool
    - name: compressAllRowGroups
      value: 
      type: 
    - name: compactLargeObjects
      value: 
      type: 
    - name: compressionDelay
      value: 
      type: 
    - name: dropExistingIndex
      value: 
      type: 
    - name: hasSparseColumn
      value: false
      type: bool
    - name: isFileTableDefined
      value: false
      type: bool
    - name: isFullTextKey
      value: false
      type: bool
    - name: isIndexOnComputed
      value: 
      type: 
    - name: isIndexOnTable
      value: 
      type: 
    - name: isMemoryOptimized
      value: false
      type: bool
    - name: isOnlineRebuildSupported
      value: 
      type: 
    - name: isOptimizedForSequentialKey
      value: false
      type: bool
    - name: lowPriorityAbortAfterWait
      value: 
      type: 
    - name: lowPriorityMaxDuration
      value: 
      type: 
    - name: lowPriorityMaxDuration
      value: 
      type: 
    - name: onlineIndexOperation
      value: 
      type: 
    - name: resumableIndexOperation
      value: 
      type: 
    - name: resumableMaxDuration
      value: 
      type: 
    - name: resumableOperationState
      value: None
      type: enum
  databaseId: database.adventureworks2022
  script: ""
triggers: []
columns:
- type: TableColumn
  id: table.sales.personcreditcard.column.businessentityid
  description: Business entity identification number. Foreign key to Person.BusinessEntityID.
  name: BusinessEntityID
  dataType: INT
  dataTypeRef: 
  maxLengthBytes: 4
  precision: 10
  scale: 0
  isNullable: false
  isComputed: false
  computedText: ''
  isIdentity: false
  identityIncrement: 0
  identitySeed: 0
  inPrimaryKey: true
  isForeignKey: true
  foreignKeys:
  - name: FK_PersonCreditCard_Person_BusinessEntityID
    id: table.sales.personcreditcard.foreignkey.fk_personcreditcard_person_businessentityid
    type: ForeignKeyRef
  default: 
  collation: ''
  isFileStream: false
  isFullTextIndexed: false
  databaseId: database.adventureworks2022
  script: ""
- type: TableColumn
  id: table.sales.personcreditcard.column.creditcardid
  description: Credit card identification number. Foreign key to CreditCard.CreditCardID.
  name: CreditCardID
  dataType: INT
  dataTypeRef: 
  maxLengthBytes: 4
  precision: 10
  scale: 0
  isNullable: false
  isComputed: false
  computedText: ''
  isIdentity: false
  identityIncrement: 0
  identitySeed: 0
  inPrimaryKey: true
  isForeignKey: true
  foreignKeys:
  - name: FK_PersonCreditCard_CreditCard_CreditCardID
    id: table.sales.personcreditcard.foreignkey.fk_personcreditcard_creditcard_creditcardid
    type: ForeignKeyRef
  default: 
  collation: ''
  isFileStream: false
  isFullTextIndexed: false
  databaseId: database.adventureworks2022
  script: ""
- type: TableColumn
  id: table.sales.personcreditcard.column.modifieddate
  description: Date and time the record was last updated.
  name: ModifiedDate
  dataType: DATETIME
  dataTypeRef: 
  maxLengthBytes: 8
  precision: 23
  scale: 3
  isNullable: false
  isComputed: false
  computedText: ''
  isIdentity: false
  identityIncrement: 0
  identitySeed: 0
  inPrimaryKey: false
  isForeignKey: false
  foreignKeys: []
  default: (getdate())
  collation: ''
  isFileStream: false
  isFullTextIndexed: false
  databaseId: database.adventureworks2022
  script: ""
databaseId: database.adventureworks2022
script: |+
  SET ANSI_NULLS ON
  GO

  SET QUOTED_IDENTIFIER ON
  GO

  CREATE TABLE [Sales].[PersonCreditCard](
  	[BusinessEntityID] [int] NOT NULL,
  	[CreditCardID] [int] NOT NULL,
  	[ModifiedDate] [datetime] NOT NULL,
   CONSTRAINT [PK_PersonCreditCard_BusinessEntityID_CreditCardID] PRIMARY KEY CLUSTERED
  (
  	[BusinessEntityID] ASC,
  	[CreditCardID] ASC
  )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
  ) ON [PRIMARY]

  GO

  ALTER TABLE [Sales].[PersonCreditCard] ADD  CONSTRAINT [DF_PersonCreditCard_ModifiedDate]  DEFAULT (getdate()) FOR [ModifiedDate]
  GO

  ALTER TABLE [Sales].[PersonCreditCard]  WITH CHECK ADD  CONSTRAINT [FK_PersonCreditCard_CreditCard_CreditCardID] FOREIGN KEY([CreditCardID])
  REFERENCES [Sales].[CreditCard] ([CreditCardID])
  GO

  ALTER TABLE [Sales].[PersonCreditCard] CHECK CONSTRAINT [FK_PersonCreditCard_CreditCard_CreditCardID]
  GO

  ALTER TABLE [Sales].[PersonCreditCard]  WITH CHECK ADD  CONSTRAINT [FK_PersonCreditCard_Person_BusinessEntityID] FOREIGN KEY([BusinessEntityID])
  REFERENCES [Person].[Person] ([BusinessEntityID])
  GO

  ALTER TABLE [Sales].[PersonCreditCard] CHECK CONSTRAINT [FK_PersonCreditCard_Person_BusinessEntityID]
  GO

