### YamlMime:DocDB
type: Table
id: table.purchasing.purchaseorderheader
description: General purchase order information. See PurchaseOrderDetail.
createdAt: 2023-05-08T12:07:29.5430000
lastModifiedAt: 2023-05-08T12:07:39.4200000
name: Purchasing.PurchaseOrderHeader
foreignKeys:
- type: ForeignKey
  id: table.purchasing.purchaseorderheader.foreignkey.fk_purchaseorderheader_employee_employeeid
  description: Foreign key constraint referencing Employee.EmployeeID.
  createdAt: 0001-01-01T00:00:00.0000000
  lastModifiedAt: 0001-01-01T00:00:00.0000000
  name: FK_PurchaseOrderHeader_Employee_EmployeeID
  columns:
  - name: EmployeeID
    id: table.purchasing.purchaseorderheader.column.employeeid
    type: TableColumnRef
  isChecked: true
  referencedKey: PK_Employee_BusinessEntityID
  referencedTable:
    name: '[HumanResources].[Employee]'
    id: table.humanresources.employee
    type: TableRef
  deleteAction: 
  updateAction: 
  script: ""
- type: ForeignKey
  id: table.purchasing.purchaseorderheader.foreignkey.fk_purchaseorderheader_shipmethod_shipmethodid
  description: Foreign key constraint referencing ShipMethod.ShipMethodID.
  createdAt: 0001-01-01T00:00:00.0000000
  lastModifiedAt: 0001-01-01T00:00:00.0000000
  name: FK_PurchaseOrderHeader_ShipMethod_ShipMethodID
  columns:
  - name: ShipMethodID
    id: table.purchasing.purchaseorderheader.column.shipmethodid
    type: TableColumnRef
  isChecked: true
  referencedKey: PK_ShipMethod_ShipMethodID
  referencedTable:
    name: '[Purchasing].[ShipMethod]'
    id: table.purchasing.shipmethod
    type: TableRef
  deleteAction: 
  updateAction: 
  script: ""
- type: ForeignKey
  id: table.purchasing.purchaseorderheader.foreignkey.fk_purchaseorderheader_vendor_vendorid
  description: Foreign key constraint referencing Vendor.VendorID.
  createdAt: 0001-01-01T00:00:00.0000000
  lastModifiedAt: 0001-01-01T00:00:00.0000000
  name: FK_PurchaseOrderHeader_Vendor_VendorID
  columns:
  - name: VendorID
    id: table.purchasing.purchaseorderheader.column.vendorid
    type: TableColumnRef
  isChecked: true
  referencedKey: PK_Vendor_BusinessEntityID
  referencedTable:
    name: '[Purchasing].[Vendor]'
    id: table.purchasing.vendor
    type: TableRef
  deleteAction: 
  updateAction: 
  script: ""
checks:
- type: CheckConstraint
  id: table.purchasing.purchaseorderheader.check.ck_purchaseorderheader_freight
  description: Check constraint [Freight] >= (0.00)
  createdAt: 0001-01-01T00:00:00.0000000
  lastModifiedAt: 0001-01-01T00:00:00.0000000
  name: CK_PurchaseOrderHeader_Freight
  isChecked: true
  isEnabled: true
  constraintText: ([Freight]>=(0.00))
  script: ""
- type: CheckConstraint
  id: table.purchasing.purchaseorderheader.check.ck_purchaseorderheader_shipdate
  description: Check constraint [ShipDate] >= [OrderDate] OR [ShipDate] IS NULL
  createdAt: 0001-01-01T00:00:00.0000000
  lastModifiedAt: 0001-01-01T00:00:00.0000000
  name: CK_PurchaseOrderHeader_ShipDate
  isChecked: true
  isEnabled: true
  constraintText: ([ShipDate]>=[OrderDate] OR [ShipDate] IS NULL)
  script: ""
- type: CheckConstraint
  id: table.purchasing.purchaseorderheader.check.ck_purchaseorderheader_status
  description: Check constraint [Status] BETWEEN (1) AND (4)
  createdAt: 0001-01-01T00:00:00.0000000
  lastModifiedAt: 0001-01-01T00:00:00.0000000
  name: CK_PurchaseOrderHeader_Status
  isChecked: true
  isEnabled: true
  constraintText: ([Status]>=(1) AND [Status]<=(4))
  script: ""
- type: CheckConstraint
  id: table.purchasing.purchaseorderheader.check.ck_purchaseorderheader_subtotal
  description: Check constraint [SubTotal] >= (0.00)
  createdAt: 0001-01-01T00:00:00.0000000
  lastModifiedAt: 0001-01-01T00:00:00.0000000
  name: CK_PurchaseOrderHeader_SubTotal
  isChecked: true
  isEnabled: true
  constraintText: ([SubTotal]>=(0.00))
  script: ""
- type: CheckConstraint
  id: table.purchasing.purchaseorderheader.check.ck_purchaseorderheader_taxamt
  description: Check constraint [TaxAmt] >= (0.00)
  createdAt: 0001-01-01T00:00:00.0000000
  lastModifiedAt: 0001-01-01T00:00:00.0000000
  name: CK_PurchaseOrderHeader_TaxAmt
  isChecked: true
  isEnabled: true
  constraintText: ([TaxAmt]>=(0.00))
  script: ""
partitionInfo:
  isPartitioned: false
  columns: []
  partitionScheme: 
  fileGroup: 
indexes: []
triggers:
- type: DmlTrigger
  id: table.purchasing.purchaseorderheader.trigger.upurchaseorderheader
  description: AFTER UPDATE trigger that updates the RevisionNumber and ModifiedDate columns in the PurchaseOrderHeader table.
  createdAt: 0001-01-01T00:00:00.0000000
  lastModifiedAt: 0001-01-01T00:00:00.0000000
  name: Purchasing.uPurchaseOrderHeader
  isEnabled: true
  isSchemaBound: false
  isInsteadOf: false
  onDelete: false
  onUpdate: true
  onInsert: false
  script: ""
columns:
- type: TableColumn
  id: table.purchasing.purchaseorderheader.column.purchaseorderid
  description: Primary key.
  createdAt: 0001-01-01T00:00:00.0000000
  lastModifiedAt: 0001-01-01T00:00:00.0000000
  name: PurchaseOrderID
  dataType: INT
  maxLengthBytes: 4
  precision: 10
  scale: 0
  isNullable: false
  isComputed: false
  computedText: ''
  isIdentity: true
  identityIncrement: 1
  identitySeed: 1
  inPrimaryKey: true
  isForeignKey: false
  foreignKeys: []
  default: 
  collation: ''
  isFileStream: false
  isFullTextIndexed: false
  script: ""
- type: TableColumn
  id: table.purchasing.purchaseorderheader.column.revisionnumber
  description: Incremental number to track changes to the purchase order over time.
  createdAt: 0001-01-01T00:00:00.0000000
  lastModifiedAt: 0001-01-01T00:00:00.0000000
  name: RevisionNumber
  dataType: TINYINT
  maxLengthBytes: 1
  precision: 3
  scale: 0
  isNullable: false
  isComputed: false
  computedText: ''
  isIdentity: false
  identityIncrement: 0
  identitySeed: 0
  inPrimaryKey: false
  isForeignKey: false
  foreignKeys: []
  default: ((0))
  collation: ''
  isFileStream: false
  isFullTextIndexed: false
  script: ""
- type: TableColumn
  id: table.purchasing.purchaseorderheader.column.status
  description: Order current status. 1 = Pending; 2 = Approved; 3 = Rejected; 4 = Complete
  createdAt: 0001-01-01T00:00:00.0000000
  lastModifiedAt: 0001-01-01T00:00:00.0000000
  name: Status
  dataType: TINYINT
  maxLengthBytes: 1
  precision: 3
  scale: 0
  isNullable: false
  isComputed: false
  computedText: ''
  isIdentity: false
  identityIncrement: 0
  identitySeed: 0
  inPrimaryKey: false
  isForeignKey: false
  foreignKeys: []
  default: ((1))
  collation: ''
  isFileStream: false
  isFullTextIndexed: false
  script: ""
- type: TableColumn
  id: table.purchasing.purchaseorderheader.column.employeeid
  description: Employee who created the purchase order. Foreign key to Employee.BusinessEntityID.
  createdAt: 0001-01-01T00:00:00.0000000
  lastModifiedAt: 0001-01-01T00:00:00.0000000
  name: EmployeeID
  dataType: INT
  maxLengthBytes: 4
  precision: 10
  scale: 0
  isNullable: false
  isComputed: false
  computedText: ''
  isIdentity: false
  identityIncrement: 0
  identitySeed: 0
  inPrimaryKey: false
  isForeignKey: true
  foreignKeys:
  - name: FK_PurchaseOrderHeader_Employee_EmployeeID
    id: table.purchasing.purchaseorderheader.foreignkey.fk_purchaseorderheader_employee_employeeid
    type: ForeignKeyRef
  default: 
  collation: ''
  isFileStream: false
  isFullTextIndexed: false
  script: ""
- type: TableColumn
  id: table.purchasing.purchaseorderheader.column.vendorid
  description: Vendor with whom the purchase order is placed. Foreign key to Vendor.BusinessEntityID.
  createdAt: 0001-01-01T00:00:00.0000000
  lastModifiedAt: 0001-01-01T00:00:00.0000000
  name: VendorID
  dataType: INT
  maxLengthBytes: 4
  precision: 10
  scale: 0
  isNullable: false
  isComputed: false
  computedText: ''
  isIdentity: false
  identityIncrement: 0
  identitySeed: 0
  inPrimaryKey: false
  isForeignKey: true
  foreignKeys:
  - name: FK_PurchaseOrderHeader_Vendor_VendorID
    id: table.purchasing.purchaseorderheader.foreignkey.fk_purchaseorderheader_vendor_vendorid
    type: ForeignKeyRef
  default: 
  collation: ''
  isFileStream: false
  isFullTextIndexed: false
  script: ""
- type: TableColumn
  id: table.purchasing.purchaseorderheader.column.shipmethodid
  description: Shipping method. Foreign key to ShipMethod.ShipMethodID.
  createdAt: 0001-01-01T00:00:00.0000000
  lastModifiedAt: 0001-01-01T00:00:00.0000000
  name: ShipMethodID
  dataType: INT
  maxLengthBytes: 4
  precision: 10
  scale: 0
  isNullable: false
  isComputed: false
  computedText: ''
  isIdentity: false
  identityIncrement: 0
  identitySeed: 0
  inPrimaryKey: false
  isForeignKey: true
  foreignKeys:
  - name: FK_PurchaseOrderHeader_ShipMethod_ShipMethodID
    id: table.purchasing.purchaseorderheader.foreignkey.fk_purchaseorderheader_shipmethod_shipmethodid
    type: ForeignKeyRef
  default: 
  collation: ''
  isFileStream: false
  isFullTextIndexed: false
  script: ""
- type: TableColumn
  id: table.purchasing.purchaseorderheader.column.orderdate
  description: Purchase order creation date.
  createdAt: 0001-01-01T00:00:00.0000000
  lastModifiedAt: 0001-01-01T00:00:00.0000000
  name: OrderDate
  dataType: DATETIME
  maxLengthBytes: 8
  precision: 23
  scale: 3
  isNullable: false
  isComputed: false
  computedText: ''
  isIdentity: false
  identityIncrement: 0
  identitySeed: 0
  inPrimaryKey: false
  isForeignKey: false
  foreignKeys: []
  default: (getdate())
  collation: ''
  isFileStream: false
  isFullTextIndexed: false
  script: ""
- type: TableColumn
  id: table.purchasing.purchaseorderheader.column.shipdate
  description: Estimated shipment date from the vendor.
  createdAt: 0001-01-01T00:00:00.0000000
  lastModifiedAt: 0001-01-01T00:00:00.0000000
  name: ShipDate
  dataType: DATETIME
  maxLengthBytes: 8
  precision: 23
  scale: 3
  isNullable: true
  isComputed: false
  computedText: ''
  isIdentity: false
  identityIncrement: 0
  identitySeed: 0
  inPrimaryKey: false
  isForeignKey: false
  foreignKeys: []
  default: 
  collation: ''
  isFileStream: false
  isFullTextIndexed: false
  script: ""
- type: TableColumn
  id: table.purchasing.purchaseorderheader.column.subtotal
  description: Purchase order subtotal. Computed as SUM(PurchaseOrderDetail.LineTotal)for the appropriate PurchaseOrderID.
  createdAt: 0001-01-01T00:00:00.0000000
  lastModifiedAt: 0001-01-01T00:00:00.0000000
  name: SubTotal
  dataType: MONEY
  maxLengthBytes: 8
  precision: 19
  scale: 4
  isNullable: false
  isComputed: false
  computedText: ''
  isIdentity: false
  identityIncrement: 0
  identitySeed: 0
  inPrimaryKey: false
  isForeignKey: false
  foreignKeys: []
  default: ((0.00))
  collation: ''
  isFileStream: false
  isFullTextIndexed: false
  script: ""
- type: TableColumn
  id: table.purchasing.purchaseorderheader.column.taxamt
  description: Tax amount.
  createdAt: 0001-01-01T00:00:00.0000000
  lastModifiedAt: 0001-01-01T00:00:00.0000000
  name: TaxAmt
  dataType: MONEY
  maxLengthBytes: 8
  precision: 19
  scale: 4
  isNullable: false
  isComputed: false
  computedText: ''
  isIdentity: false
  identityIncrement: 0
  identitySeed: 0
  inPrimaryKey: false
  isForeignKey: false
  foreignKeys: []
  default: ((0.00))
  collation: ''
  isFileStream: false
  isFullTextIndexed: false
  script: ""
- type: TableColumn
  id: table.purchasing.purchaseorderheader.column.freight
  description: Shipping cost.
  createdAt: 0001-01-01T00:00:00.0000000
  lastModifiedAt: 0001-01-01T00:00:00.0000000
  name: Freight
  dataType: MONEY
  maxLengthBytes: 8
  precision: 19
  scale: 4
  isNullable: false
  isComputed: false
  computedText: ''
  isIdentity: false
  identityIncrement: 0
  identitySeed: 0
  inPrimaryKey: false
  isForeignKey: false
  foreignKeys: []
  default: ((0.00))
  collation: ''
  isFileStream: false
  isFullTextIndexed: false
  script: ""
- type: TableColumn
  id: table.purchasing.purchaseorderheader.column.totaldue
  description: Total due to vendor. Computed as Subtotal + TaxAmt + Freight.
  createdAt: 0001-01-01T00:00:00.0000000
  lastModifiedAt: 0001-01-01T00:00:00.0000000
  name: TotalDue
  dataType: MONEY
  maxLengthBytes: 8
  precision: 19
  scale: 4
  isNullable: false
  isComputed: true
  computedText: (isnull(([SubTotal]+[TaxAmt])+[Freight],(0)))
  isIdentity: false
  identityIncrement: 0
  identitySeed: 0
  inPrimaryKey: false
  isForeignKey: false
  foreignKeys: []
  default: 
  collation: ''
  isFileStream: false
  isFullTextIndexed: false
  script: ""
- type: TableColumn
  id: table.purchasing.purchaseorderheader.column.modifieddate
  description: Date and time the record was last updated.
  createdAt: 0001-01-01T00:00:00.0000000
  lastModifiedAt: 0001-01-01T00:00:00.0000000
  name: ModifiedDate
  dataType: DATETIME
  maxLengthBytes: 8
  precision: 23
  scale: 3
  isNullable: false
  isComputed: false
  computedText: ''
  isIdentity: false
  identityIncrement: 0
  identitySeed: 0
  inPrimaryKey: false
  isForeignKey: false
  foreignKeys: []
  default: (getdate())
  collation: ''
  isFileStream: false
  isFullTextIndexed: false
  script: ""
script: |+
  SET ANSI_NULLS ON
  GO

  SET QUOTED_IDENTIFIER ON
  GO

  CREATE TABLE [Purchasing].[PurchaseOrderHeader](
  	[PurchaseOrderID] [int] IDENTITY(1,1) NOT NULL,
  	[RevisionNumber] [tinyint] NOT NULL,
  	[Status] [tinyint] NOT NULL,
  	[EmployeeID] [int] NOT NULL,
  	[VendorID] [int] NOT NULL,
  	[ShipMethodID] [int] NOT NULL,
  	[OrderDate] [datetime] NOT NULL,
  	[ShipDate] [datetime] NULL,
  	[SubTotal] [money] NOT NULL,
  	[TaxAmt] [money] NOT NULL,
  	[Freight] [money] NOT NULL,
  	[TotalDue]  AS (isnull(([SubTotal]+[TaxAmt])+[Freight],(0))) PERSISTED NOT NULL,
  	[ModifiedDate] [datetime] NOT NULL,
   CONSTRAINT [PK_PurchaseOrderHeader_PurchaseOrderID] PRIMARY KEY CLUSTERED
  (
  	[PurchaseOrderID] ASC
  )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
  ) ON [PRIMARY]

  GO

  CREATE NONCLUSTERED INDEX [IX_PurchaseOrderHeader_EmployeeID] ON [Purchasing].[PurchaseOrderHeader]
  (
  	[EmployeeID] ASC
  )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
  GO

  CREATE NONCLUSTERED INDEX [IX_PurchaseOrderHeader_VendorID] ON [Purchasing].[PurchaseOrderHeader]
  (
  	[VendorID] ASC
  )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
  GO

  ALTER TABLE [Purchasing].[PurchaseOrderHeader] ADD  CONSTRAINT [DF_PurchaseOrderHeader_RevisionNumber]  DEFAULT ((0)) FOR [RevisionNumber]
  GO

  ALTER TABLE [Purchasing].[PurchaseOrderHeader] ADD  CONSTRAINT [DF_PurchaseOrderHeader_Status]  DEFAULT ((1)) FOR [Status]
  GO

  ALTER TABLE [Purchasing].[PurchaseOrderHeader] ADD  CONSTRAINT [DF_PurchaseOrderHeader_OrderDate]  DEFAULT (getdate()) FOR [OrderDate]
  GO

  ALTER TABLE [Purchasing].[PurchaseOrderHeader] ADD  CONSTRAINT [DF_PurchaseOrderHeader_SubTotal]  DEFAULT ((0.00)) FOR [SubTotal]
  GO

  ALTER TABLE [Purchasing].[PurchaseOrderHeader] ADD  CONSTRAINT [DF_PurchaseOrderHeader_TaxAmt]  DEFAULT ((0.00)) FOR [TaxAmt]
  GO

  ALTER TABLE [Purchasing].[PurchaseOrderHeader] ADD  CONSTRAINT [DF_PurchaseOrderHeader_Freight]  DEFAULT ((0.00)) FOR [Freight]
  GO

  ALTER TABLE [Purchasing].[PurchaseOrderHeader] ADD  CONSTRAINT [DF_PurchaseOrderHeader_ModifiedDate]  DEFAULT (getdate()) FOR [ModifiedDate]
  GO

  ALTER TABLE [Purchasing].[PurchaseOrderHeader]  WITH CHECK ADD  CONSTRAINT [FK_PurchaseOrderHeader_Employee_EmployeeID] FOREIGN KEY([EmployeeID])
  REFERENCES [HumanResources].[Employee] ([BusinessEntityID])
  GO

  ALTER TABLE [Purchasing].[PurchaseOrderHeader] CHECK CONSTRAINT [FK_PurchaseOrderHeader_Employee_EmployeeID]
  GO

  ALTER TABLE [Purchasing].[PurchaseOrderHeader]  WITH CHECK ADD  CONSTRAINT [FK_PurchaseOrderHeader_ShipMethod_ShipMethodID] FOREIGN KEY([ShipMethodID])
  REFERENCES [Purchasing].[ShipMethod] ([ShipMethodID])
  GO

  ALTER TABLE [Purchasing].[PurchaseOrderHeader] CHECK CONSTRAINT [FK_PurchaseOrderHeader_ShipMethod_ShipMethodID]
  GO

  ALTER TABLE [Purchasing].[PurchaseOrderHeader]  WITH CHECK ADD  CONSTRAINT [FK_PurchaseOrderHeader_Vendor_VendorID] FOREIGN KEY([VendorID])
  REFERENCES [Purchasing].[Vendor] ([BusinessEntityID])
  GO

  ALTER TABLE [Purchasing].[PurchaseOrderHeader] CHECK CONSTRAINT [FK_PurchaseOrderHeader_Vendor_VendorID]
  GO

  ALTER TABLE [Purchasing].[PurchaseOrderHeader]  WITH CHECK ADD  CONSTRAINT [CK_PurchaseOrderHeader_Freight] CHECK  (([Freight]>=(0.00)))
  GO

  ALTER TABLE [Purchasing].[PurchaseOrderHeader] CHECK CONSTRAINT [CK_PurchaseOrderHeader_Freight]
  GO

  ALTER TABLE [Purchasing].[PurchaseOrderHeader]  WITH CHECK ADD  CONSTRAINT [CK_PurchaseOrderHeader_ShipDate] CHECK  (([ShipDate]>=[OrderDate] OR [ShipDate] IS NULL))
  GO

  ALTER TABLE [Purchasing].[PurchaseOrderHeader] CHECK CONSTRAINT [CK_PurchaseOrderHeader_ShipDate]
  GO

  ALTER TABLE [Purchasing].[PurchaseOrderHeader]  WITH CHECK ADD  CONSTRAINT [CK_PurchaseOrderHeader_Status] CHECK  (([Status]>=(1) AND [Status]<=(4)))
  GO

  ALTER TABLE [Purchasing].[PurchaseOrderHeader] CHECK CONSTRAINT [CK_PurchaseOrderHeader_Status]
  GO

  ALTER TABLE [Purchasing].[PurchaseOrderHeader]  WITH CHECK ADD  CONSTRAINT [CK_PurchaseOrderHeader_SubTotal] CHECK  (([SubTotal]>=(0.00)))
  GO

  ALTER TABLE [Purchasing].[PurchaseOrderHeader] CHECK CONSTRAINT [CK_PurchaseOrderHeader_SubTotal]
  GO

  ALTER TABLE [Purchasing].[PurchaseOrderHeader]  WITH CHECK ADD  CONSTRAINT [CK_PurchaseOrderHeader_TaxAmt] CHECK  (([TaxAmt]>=(0.00)))
  GO

  ALTER TABLE [Purchasing].[PurchaseOrderHeader] CHECK CONSTRAINT [CK_PurchaseOrderHeader_TaxAmt]
  GO

  SET ANSI_NULLS ON
  GO

  SET QUOTED_IDENTIFIER ON
  GO

  CREATE TRIGGER [Purchasing].[uPurchaseOrderHeader] ON [Purchasing].[PurchaseOrderHeader]
  AFTER UPDATE AS
  BEGIN
      DECLARE @Count int;

      SET @Count = @@ROWCOUNT;
      IF @Count = 0
          RETURN;

      SET NOCOUNT ON;

      BEGIN TRY
          -- Update RevisionNumber for modification of any field EXCEPT the Status.
          IF NOT UPDATE([Status])
          BEGIN
              UPDATE [Purchasing].[PurchaseOrderHeader]
              SET [Purchasing].[PurchaseOrderHeader].[RevisionNumber] =
                  [Purchasing].[PurchaseOrderHeader].[RevisionNumber] + 1
              WHERE [Purchasing].[PurchaseOrderHeader].[PurchaseOrderID] IN
                  (SELECT inserted.[PurchaseOrderID] FROM inserted);
          END;
      END TRY
      BEGIN CATCH
          EXECUTE [dbo].[uspPrintError];

          -- Rollback any active or uncommittable transactions before
          -- inserting information in the ErrorLog
          IF @@TRANCOUNT > 0
          BEGIN
              ROLLBACK TRANSACTION;
          END

          EXECUTE [dbo].[uspLogError];
      END CATCH;
  END;

  GO

  ALTER TABLE [Purchasing].[PurchaseOrderHeader] ENABLE TRIGGER [uPurchaseOrderHeader]
  GO

