### YamlMime:DocDB
type: Table
id: table.productinventory.productinventory
description: Product inventory information.
createdAt: 2023-05-08T12:07:29.5070000
lastModifiedAt: 2023-05-08T12:07:38.8030000
name: ProductInventory.ProductInventory
foreignKeys:
- type: ForeignKey
  id: table.productinventory.productinventory.foreignkey.fk_productinventory_location_locationid
  description: Foreign key constraint referencing Location.LocationID.
  createdAt: 0001-01-01T00:00:00.0000000
  lastModifiedAt: 0001-01-01T00:00:00.0000000
  name: FK_ProductInventory_Location_LocationID
  columns:
  - name: LocationID
    id: table.productinventory.productinventory.column.locationid
    type: TableColumnRef
  isChecked: true
  referencedKey: PK_Location_LocationID
  referencedTable:
    name: '[Location].[Location]'
    id: table.location.location
    type: TableRef
  deleteAction: 
  updateAction: 
  script: ""
- type: ForeignKey
  id: table.productinventory.productinventory.foreignkey.fk_productinventory_product_productid
  description: Foreign key constraint referencing Product.ProductID.
  createdAt: 0001-01-01T00:00:00.0000000
  lastModifiedAt: 0001-01-01T00:00:00.0000000
  name: FK_ProductInventory_Product_ProductID
  columns:
  - name: ProductID
    id: table.productinventory.productinventory.column.productid
    type: TableColumnRef
  isChecked: true
  referencedKey: PK_Product_ProductID
  referencedTable:
    name: '[Product].[Product]'
    id: table.product.product
    type: TableRef
  deleteAction: 
  updateAction: 
  script: ""
checks:
- type: CheckConstraint
  id: table.productinventory.productinventory.check.ck_productinventory_bin
  description: Check constraint [Bin] BETWEEN (0) AND (100)
  createdAt: 0001-01-01T00:00:00.0000000
  lastModifiedAt: 0001-01-01T00:00:00.0000000
  name: CK_ProductInventory_Bin
  isChecked: true
  isEnabled: true
  constraintText: ([Bin]>=(0) AND [Bin]<=(100))
  script: ""
- type: CheckConstraint
  id: table.productinventory.productinventory.check.ck_productinventory_shelf
  description: Check constraint [Shelf] like '[A-Za-z]' OR [Shelf]='N/A'
  createdAt: 0001-01-01T00:00:00.0000000
  lastModifiedAt: 0001-01-01T00:00:00.0000000
  name: CK_ProductInventory_Shelf
  isChecked: true
  isEnabled: true
  constraintText: ([Shelf] like '[A-Za-z]' OR [Shelf]='N/A')
  script: ""
partitionInfo:
  isPartitioned: false
  columns: []
  partitionScheme: 
  fileGroup: 
indexes: []
triggers: []
columns:
- type: TableColumn
  id: table.productinventory.productinventory.column.productid
  description: Product identification number. Foreign key to Product.ProductID.
  createdAt: 0001-01-01T00:00:00.0000000
  lastModifiedAt: 0001-01-01T00:00:00.0000000
  name: ProductID
  dataType: INT
  maxLengthBytes: 4
  precision: 10
  scale: 0
  isNullable: false
  isComputed: false
  computedText: ''
  isIdentity: false
  identityIncrement: 0
  identitySeed: 0
  inPrimaryKey: true
  isForeignKey: true
  foreignKeys:
  - name: FK_ProductInventory_Product_ProductID
    id: table.productinventory.productinventory.foreignkey.fk_productinventory_product_productid
    type: ForeignKeyRef
  default: 
  collation: ''
  isFileStream: false
  isFullTextIndexed: false
  script: ""
- type: TableColumn
  id: table.productinventory.productinventory.column.locationid
  description: 'Inventory location identification number. Foreign key to Location.LocationID. '
  createdAt: 0001-01-01T00:00:00.0000000
  lastModifiedAt: 0001-01-01T00:00:00.0000000
  name: LocationID
  dataType: SMALLINT
  maxLengthBytes: 2
  precision: 5
  scale: 0
  isNullable: false
  isComputed: false
  computedText: ''
  isIdentity: false
  identityIncrement: 0
  identitySeed: 0
  inPrimaryKey: true
  isForeignKey: true
  foreignKeys:
  - name: FK_ProductInventory_Location_LocationID
    id: table.productinventory.productinventory.foreignkey.fk_productinventory_location_locationid
    type: ForeignKeyRef
  default: 
  collation: ''
  isFileStream: false
  isFullTextIndexed: false
  script: ""
- type: TableColumn
  id: table.productinventory.productinventory.column.shelf
  description: Storage compartment within an inventory location.
  createdAt: 0001-01-01T00:00:00.0000000
  lastModifiedAt: 0001-01-01T00:00:00.0000000
  name: Shelf
  dataType: NVARCHAR(10)
  maxLengthBytes: 10
  precision: 0
  scale: 0
  isNullable: false
  isComputed: false
  computedText: ''
  isIdentity: false
  identityIncrement: 0
  identitySeed: 0
  inPrimaryKey: false
  isForeignKey: false
  foreignKeys: []
  default: 
  collation: SQL_Latin1_General_CP1_CI_AS
  isFileStream: false
  isFullTextIndexed: false
  script: ""
- type: TableColumn
  id: table.productinventory.productinventory.column.bin
  description: Storage container on a shelf in an inventory location.
  createdAt: 0001-01-01T00:00:00.0000000
  lastModifiedAt: 0001-01-01T00:00:00.0000000
  name: Bin
  dataType: TINYINT
  maxLengthBytes: 1
  precision: 3
  scale: 0
  isNullable: false
  isComputed: false
  computedText: ''
  isIdentity: false
  identityIncrement: 0
  identitySeed: 0
  inPrimaryKey: false
  isForeignKey: false
  foreignKeys: []
  default: 
  collation: ''
  isFileStream: false
  isFullTextIndexed: false
  script: ""
- type: TableColumn
  id: table.productinventory.productinventory.column.quantity
  description: Quantity of products in the inventory location.
  createdAt: 0001-01-01T00:00:00.0000000
  lastModifiedAt: 0001-01-01T00:00:00.0000000
  name: Quantity
  dataType: SMALLINT
  maxLengthBytes: 2
  precision: 5
  scale: 0
  isNullable: false
  isComputed: false
  computedText: ''
  isIdentity: false
  identityIncrement: 0
  identitySeed: 0
  inPrimaryKey: false
  isForeignKey: false
  foreignKeys: []
  default: ((0))
  collation: ''
  isFileStream: false
  isFullTextIndexed: false
  script: ""
- type: TableColumn
  id: table.productinventory.productinventory.column.rowguid
  description: ROWGUIDCOL number uniquely identifying the record. Used to support a merge replication sample.
  createdAt: 0001-01-01T00:00:00.0000000
  lastModifiedAt: 0001-01-01T00:00:00.0000000
  name: rowguid
  dataType: UNIQUEIDENTIFIER
  maxLengthBytes: 16
  precision: 0
  scale: 0
  isNullable: false
  isComputed: false
  computedText: ''
  isIdentity: false
  identityIncrement: 0
  identitySeed: 0
  inPrimaryKey: false
  isForeignKey: false
  foreignKeys: []
  default: (newid())
  collation: ''
  isFileStream: false
  isFullTextIndexed: false
  script: ""
- type: TableColumn
  id: table.productinventory.productinventory.column.modifieddate
  description: Date and time the record was last updated.
  createdAt: 0001-01-01T00:00:00.0000000
  lastModifiedAt: 0001-01-01T00:00:00.0000000
  name: ModifiedDate
  dataType: DATETIME
  maxLengthBytes: 8
  precision: 23
  scale: 3
  isNullable: false
  isComputed: false
  computedText: ''
  isIdentity: false
  identityIncrement: 0
  identitySeed: 0
  inPrimaryKey: false
  isForeignKey: false
  foreignKeys: []
  default: (getdate())
  collation: ''
  isFileStream: false
  isFullTextIndexed: false
  script: ""
script: |+
  SET ANSI_NULLS ON
  GO

  SET QUOTED_IDENTIFIER ON
  GO

  CREATE TABLE [Production].[ProductInventory](
  	[ProductID] [int] NOT NULL,
  	[LocationID] [smallint] NOT NULL,
  	[Shelf] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
  	[Bin] [tinyint] NOT NULL,
  	[Quantity] [smallint] NOT NULL,
  	[rowguid] [uniqueidentifier] ROWGUIDCOL  NOT NULL,
  	[ModifiedDate] [datetime] NOT NULL,
   CONSTRAINT [PK_ProductInventory_ProductID_LocationID] PRIMARY KEY CLUSTERED
  (
  	[ProductID] ASC,
  	[LocationID] ASC
  )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
  ) ON [PRIMARY]

  GO

  ALTER TABLE [Production].[ProductInventory] ADD  CONSTRAINT [DF_ProductInventory_Quantity]  DEFAULT ((0)) FOR [Quantity]
  GO

  ALTER TABLE [Production].[ProductInventory] ADD  CONSTRAINT [DF_ProductInventory_rowguid]  DEFAULT (newid()) FOR [rowguid]
  GO

  ALTER TABLE [Production].[ProductInventory] ADD  CONSTRAINT [DF_ProductInventory_ModifiedDate]  DEFAULT (getdate()) FOR [ModifiedDate]
  GO

  ALTER TABLE [Production].[ProductInventory]  WITH CHECK ADD  CONSTRAINT [FK_ProductInventory_Location_LocationID] FOREIGN KEY([LocationID])
  REFERENCES [Production].[Location] ([LocationID])
  GO

  ALTER TABLE [Production].[ProductInventory] CHECK CONSTRAINT [FK_ProductInventory_Location_LocationID]
  GO

  ALTER TABLE [Production].[ProductInventory]  WITH CHECK ADD  CONSTRAINT [FK_ProductInventory_Product_ProductID] FOREIGN KEY([ProductID])
  REFERENCES [Production].[Product] ([ProductID])
  GO

  ALTER TABLE [Production].[ProductInventory] CHECK CONSTRAINT [FK_ProductInventory_Product_ProductID]
  GO

  ALTER TABLE [Production].[ProductInventory]  WITH CHECK ADD  CONSTRAINT [CK_ProductInventory_Bin] CHECK  (([Bin]>=(0) AND [Bin]<=(100)))
  GO

  ALTER TABLE [Production].[ProductInventory] CHECK CONSTRAINT [CK_ProductInventory_Bin]
  GO

  ALTER TABLE [Production].[ProductInventory]  WITH CHECK ADD  CONSTRAINT [CK_ProductInventory_Shelf] CHECK  (([Shelf] like '[A-Za-z]' OR [Shelf]='N/A'))
  GO

  ALTER TABLE [Production].[ProductInventory] CHECK CONSTRAINT [CK_ProductInventory_Shelf]
  GO

