### YamlMime:DocDB
type: Table
id: table.dbo.employee
description: 
createdAt: 2024-12-12T10:28:06.9900000
lastModifiedAt: 2024-12-12T10:28:06.9930000
name: dbo.Employee
foreignKeys:
- type: ForeignKey
  id: table.dbo.employee.foreignkey.fk_dboemployee_person_businessentityid
  description: 
  createdAt: 0001-01-01T00:00:00.0000000
  lastModifiedAt: 0001-01-01T00:00:00.0000000
  name: FK_DboEmployee_Person_BusinessEntityID
  columns:
  - name: EmployeeID
    id: table.dbo.employee.column.employeeid
    type: TableColumnRef
  - name: EmployeeType
    id: table.dbo.employee.column.employeetype
    type: TableColumnRef
  isChecked: true
  referencedKey: PK_Person_BusinessEntityID
  referencedTable:
    name: '[dbo].[Person]'
    id: table.dbo.person
    type: TableRef
  deleteAction: 
  updateAction: 
  script: ""
checks: []
partitionInfo:
  isPartitioned: false
  columns: []
  partitionScheme: 
  fileGroup: 
indexes: []
triggers: []
columns:
- type: TableColumn
  id: table.dbo.employee.column.employeeid
  description: 
  createdAt: 0001-01-01T00:00:00.0000000
  lastModifiedAt: 0001-01-01T00:00:00.0000000
  name: EmployeeID
  dataType: INT
  maxLengthBytes: 4
  precision: 10
  scale: 0
  isNullable: false
  isComputed: false
  computedText: ''
  isIdentity: false
  identityIncrement: 0
  identitySeed: 0
  inPrimaryKey: true
  isForeignKey: true
  foreignKeys:
  - name: FK_DboEmployee_Person_BusinessEntityID
    id: table.dbo.employee.foreignkey.fk_dboemployee_person_businessentityid
    type: ForeignKeyRef
  default: 
  collation: ''
  isFileStream: false
  isFullTextIndexed: false
  script: ""
- type: TableColumn
  id: table.dbo.employee.column.employeetype
  description: 
  createdAt: 0001-01-01T00:00:00.0000000
  lastModifiedAt: 0001-01-01T00:00:00.0000000
  name: EmployeeType
  dataType: NCHAR(2)
  maxLengthBytes: 2
  precision: 0
  scale: 0
  isNullable: false
  isComputed: false
  computedText: ''
  isIdentity: false
  identityIncrement: 0
  identitySeed: 0
  inPrimaryKey: false
  isForeignKey: true
  foreignKeys:
  - name: FK_DboEmployee_Person_BusinessEntityID
    id: table.dbo.employee.foreignkey.fk_dboemployee_person_businessentityid
    type: ForeignKeyRef
  default: 
  collation: SQL_Latin1_General_CP1_CI_AS
  isFileStream: false
  isFullTextIndexed: false
  script: ""
script: |+
  SET ANSI_NULLS ON
  GO

  SET QUOTED_IDENTIFIER ON
  GO

  CREATE TABLE [dbo].[Employee](
  	[EmployeeID] [int] NOT NULL,
  	[EmployeeType] [nchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
   CONSTRAINT [PK_Employee_BusinessEntityID] PRIMARY KEY CLUSTERED
  (
  	[EmployeeID] ASC
  )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
  ) ON [PRIMARY]

  GO

  ALTER TABLE [dbo].[Employee]  WITH CHECK ADD  CONSTRAINT [FK_DboEmployee_Person_BusinessEntityID] FOREIGN KEY([EmployeeID], [EmployeeType])
  REFERENCES [dbo].[Person] ([BusinessEntityID], [PersonType])
  GO

  ALTER TABLE [dbo].[Employee] CHECK CONSTRAINT [FK_DboEmployee_Person_BusinessEntityID]
  GO

