### YamlMime:DocDB
type: Table
id: table.production.productmodelproductdescriptionculture
description: Cross-reference table mapping product descriptions and the language the description is written in.
name: Production.ProductModelProductDescriptionCulture
foreignKeys:
- type: ForeignKey
  id: table.production.productmodelproductdescriptionculture.foreignkey.fk_productmodelproductdescriptionculture_culture_cultureid
  description: Foreign key constraint referencing Culture.CultureID.
  name: FK_ProductModelProductDescriptionCulture_Culture_CultureID
  columns:
  - name: CultureID
    id: table.production.productmodelproductdescriptionculture.column.cultureid
    type: TableColumnRef
  isChecked: true
  referencedKey: PK_Culture_CultureID
  referencedTable:
    name: '[Production].[Culture]'
    id: table.production.culture
    type: TableRef
  deleteAction: 
  updateAction: 
  databaseId: database.adventureworks2022
  script: ""
- type: ForeignKey
  id: table.production.productmodelproductdescriptionculture.foreignkey.fk_productmodelproductdescriptionculture_productdescription_productdescriptionid
  description: Foreign key constraint referencing ProductDescription.ProductDescriptionID.
  name: FK_ProductModelProductDescriptionCulture_ProductDescription_ProductDescriptionID
  columns:
  - name: ProductDescriptionID
    id: table.production.productmodelproductdescriptionculture.column.productdescriptionid
    type: TableColumnRef
  isChecked: true
  referencedKey: PK_ProductDescription_ProductDescriptionID
  referencedTable:
    name: '[Production].[ProductDescription]'
    id: table.production.productdescription
    type: TableRef
  deleteAction: 
  updateAction: 
  databaseId: database.adventureworks2022
  script: ""
- type: ForeignKey
  id: table.production.productmodelproductdescriptionculture.foreignkey.fk_productmodelproductdescriptionculture_productmodel_productmodelid
  description: Foreign key constraint referencing ProductModel.ProductModelID.
  name: FK_ProductModelProductDescriptionCulture_ProductModel_ProductModelID
  columns:
  - name: ProductModelID
    id: table.production.productmodelproductdescriptionculture.column.productmodelid
    type: TableColumnRef
  isChecked: true
  referencedKey: PK_ProductModel_ProductModelID
  referencedTable:
    name: '[Production].[ProductModel]'
    id: table.production.productmodel
    type: TableRef
  deleteAction: 
  updateAction: 
  databaseId: database.adventureworks2022
  script: ""
checks: []
fileGroup:
  name: '[PRIMARY]'
  id: filegroup.primary
  type: FileGroupRef
fileStreamGroup: 
textFileGroup: 
partitionInfo:
  isPartitioned: false
  columns: []
  partitionScheme: 
fileTableInfo:
  isFileTable: false
  directoryName: 
  nameColumnCollation: 
  namespaceEnabled: false
indexes:
- type: Index
  id: table.production.productmodelproductdescriptionculture.index.pk_productmodelproductdescriptionculture_productmodelid_productdescriptionid_cultureid
  description: Primary key (clustered) constraint
  name: PK_ProductModelProductDescriptionCulture_ProductModelID_ProductDescriptionID_CultureID
  indexType: CLUSTERED
  indexKeyType: PRIMARY
  isDisabled: false
  isUnique: true
  isClustered: true
  filter: ''
  columns:
  - type: IndexColumn
    id: table.production.productmodelproductdescriptionculture.index.pk_productmodelproductdescriptionculture_productmodelid_productdescriptionid_cultureid.indexedcolumn.productmodelid
    description: 
    name: ProductModelID
    columnRef:
      name: ProductModelID
      id: table.production.productmodelproductdescriptionculture.column.productmodelid
      type: TableColumnRef
    isDescending: false
    isIncluded: false
    columnStoreOrderOrdinal: 0
    databaseId: database.adventureworks2022
    script: ""
  - type: IndexColumn
    id: table.production.productmodelproductdescriptionculture.index.pk_productmodelproductdescriptionculture_productmodelid_productdescriptionid_cultureid.indexedcolumn.productdescriptionid
    description: 
    name: ProductDescriptionID
    columnRef:
      name: ProductDescriptionID
      id: table.production.productmodelproductdescriptionculture.column.productdescriptionid
      type: TableColumnRef
    isDescending: false
    isIncluded: false
    columnStoreOrderOrdinal: 0
    databaseId: database.adventureworks2022
    script: ""
  - type: IndexColumn
    id: table.production.productmodelproductdescriptionculture.index.pk_productmodelproductdescriptionculture_productmodelid_productdescriptionid_cultureid.indexedcolumn.cultureid
    description: 
    name: CultureID
    columnRef:
      name: CultureID
      id: table.production.productmodelproductdescriptionculture.column.cultureid
      type: TableColumnRef
    isDescending: false
    isIncluded: false
    columnStoreOrderOrdinal: 0
    databaseId: database.adventureworks2022
    script: ""
  isPartitioned: false
  fileGroup:
    name: PRIMARY
    id: filegroup.primary
    type: FileGroupRef
  fileStreamGroup: 
  options:
  - name: general
    entries:
    - name: autoRecomputeStatistics
      value: true
      type: bool
    - name: ignoreDuplicateKeys
      value: false
      type: bool
  - name: storage
    entries:
    - name: sortInTempdb
      value: 
      type: 
    - name: fillFactor
      value: 0
      type: string
    - name: padIndex
      value: false
      type: bool
  - name: operation
    entries:
    - name: maximumDegreeOfParallelism
      value: 
      type: 
    - name: isOptimizedForSequentialKey
      value: false
      type: bool
  - name: locks
    entries:
    - name: allowPageLocks
      value: true
      type: bool
    - name: allowRowLocks
      value: true
      type: bool
  - name: spatial
    entries:
    - name: isSpatialIndex
      value: false
      type: bool
  - name: xml
    entries:
    - name: isXmlIndex
      value: false
      type: bool
  - name: miscellaneous
    entries:
    - name: hasCompressedPartitions
      value: false
      type: bool
    - name: hasXmlCompressedPartitions
      value: false
      type: bool
    - name: compressAllRowGroups
      value: 
      type: 
    - name: compactLargeObjects
      value: 
      type: 
    - name: compressionDelay
      value: 
      type: 
    - name: dropExistingIndex
      value: 
      type: 
    - name: hasSparseColumn
      value: false
      type: bool
    - name: isFileTableDefined
      value: false
      type: bool
    - name: isFullTextKey
      value: false
      type: bool
    - name: isIndexOnComputed
      value: 
      type: 
    - name: isIndexOnTable
      value: 
      type: 
    - name: isMemoryOptimized
      value: false
      type: bool
    - name: isOnlineRebuildSupported
      value: 
      type: 
    - name: isOptimizedForSequentialKey
      value: false
      type: bool
    - name: lowPriorityAbortAfterWait
      value: 
      type: 
    - name: lowPriorityMaxDuration
      value: 
      type: 
    - name: lowPriorityMaxDuration
      value: 
      type: 
    - name: onlineIndexOperation
      value: 
      type: 
    - name: resumableIndexOperation
      value: 
      type: 
    - name: resumableMaxDuration
      value: 
      type: 
    - name: resumableOperationState
      value: None
      type: enum
  databaseId: database.adventureworks2022
  script: ""
triggers: []
columns:
- type: TableColumn
  id: table.production.productmodelproductdescriptionculture.column.productmodelid
  description: Primary key. Foreign key to ProductModel.ProductModelID.
  name: ProductModelID
  dataType: INT
  dataTypeRef: 
  maxLengthBytes: 4
  precision: 10
  scale: 0
  isNullable: false
  isComputed: false
  computedText: ''
  isIdentity: false
  identityIncrement: 0
  identitySeed: 0
  inPrimaryKey: true
  isForeignKey: true
  foreignKeys:
  - name: FK_ProductModelProductDescriptionCulture_ProductModel_ProductModelID
    id: table.production.productmodelproductdescriptionculture.foreignkey.fk_productmodelproductdescriptionculture_productmodel_productmodelid
    type: ForeignKeyRef
  default: 
  collation: ''
  isFileStream: false
  isFullTextIndexed: false
  databaseId: database.adventureworks2022
  script: ""
- type: TableColumn
  id: table.production.productmodelproductdescriptionculture.column.productdescriptionid
  description: Primary key. Foreign key to ProductDescription.ProductDescriptionID.
  name: ProductDescriptionID
  dataType: INT
  dataTypeRef: 
  maxLengthBytes: 4
  precision: 10
  scale: 0
  isNullable: false
  isComputed: false
  computedText: ''
  isIdentity: false
  identityIncrement: 0
  identitySeed: 0
  inPrimaryKey: true
  isForeignKey: true
  foreignKeys:
  - name: FK_ProductModelProductDescriptionCulture_ProductDescription_ProductDescriptionID
    id: table.production.productmodelproductdescriptionculture.foreignkey.fk_productmodelproductdescriptionculture_productdescription_productdescriptionid
    type: ForeignKeyRef
  default: 
  collation: ''
  isFileStream: false
  isFullTextIndexed: false
  databaseId: database.adventureworks2022
  script: ""
- type: TableColumn
  id: table.production.productmodelproductdescriptionculture.column.cultureid
  description: Culture identification number. Foreign key to Culture.CultureID.
  name: CultureID
  dataType: NCHAR(6)
  dataTypeRef: 
  maxLengthBytes: 6
  precision: 0
  scale: 0
  isNullable: false
  isComputed: false
  computedText: ''
  isIdentity: false
  identityIncrement: 0
  identitySeed: 0
  inPrimaryKey: true
  isForeignKey: true
  foreignKeys:
  - name: FK_ProductModelProductDescriptionCulture_Culture_CultureID
    id: table.production.productmodelproductdescriptionculture.foreignkey.fk_productmodelproductdescriptionculture_culture_cultureid
    type: ForeignKeyRef
  default: 
  collation: SQL_Latin1_General_CP1_CI_AS
  isFileStream: false
  isFullTextIndexed: false
  databaseId: database.adventureworks2022
  script: ""
- type: TableColumn
  id: table.production.productmodelproductdescriptionculture.column.modifieddate
  description: Date and time the record was last updated.
  name: ModifiedDate
  dataType: DATETIME
  dataTypeRef: 
  maxLengthBytes: 8
  precision: 23
  scale: 3
  isNullable: false
  isComputed: false
  computedText: ''
  isIdentity: false
  identityIncrement: 0
  identitySeed: 0
  inPrimaryKey: false
  isForeignKey: false
  foreignKeys: []
  default: (getdate())
  collation: ''
  isFileStream: false
  isFullTextIndexed: false
  databaseId: database.adventureworks2022
  script: ""
databaseId: database.adventureworks2022
script: |+
  SET ANSI_NULLS ON
  GO

  SET QUOTED_IDENTIFIER ON
  GO

  CREATE TABLE [Production].[ProductModelProductDescriptionCulture](
  	[ProductModelID] [int] NOT NULL,
  	[ProductDescriptionID] [int] NOT NULL,
  	[CultureID] [nchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
  	[ModifiedDate] [datetime] NOT NULL,
   CONSTRAINT [PK_ProductModelProductDescriptionCulture_ProductModelID_ProductDescriptionID_CultureID] PRIMARY KEY CLUSTERED
  (
  	[ProductModelID] ASC,
  	[ProductDescriptionID] ASC,
  	[CultureID] ASC
  )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
  ) ON [PRIMARY]

  GO

  ALTER TABLE [Production].[ProductModelProductDescriptionCulture] ADD  CONSTRAINT [DF_ProductModelProductDescriptionCulture_ModifiedDate]  DEFAULT (getdate()) FOR [ModifiedDate]
  GO

  ALTER TABLE [Production].[ProductModelProductDescriptionCulture]  WITH CHECK ADD  CONSTRAINT [FK_ProductModelProductDescriptionCulture_Culture_CultureID] FOREIGN KEY([CultureID])
  REFERENCES [Production].[Culture] ([CultureID])
  GO

  ALTER TABLE [Production].[ProductModelProductDescriptionCulture] CHECK CONSTRAINT [FK_ProductModelProductDescriptionCulture_Culture_CultureID]
  GO

  ALTER TABLE [Production].[ProductModelProductDescriptionCulture]  WITH CHECK ADD  CONSTRAINT [FK_ProductModelProductDescriptionCulture_ProductDescription_ProductDescriptionID] FOREIGN KEY([ProductDescriptionID])
  REFERENCES [Production].[ProductDescription] ([ProductDescriptionID])
  GO

  ALTER TABLE [Production].[ProductModelProductDescriptionCulture] CHECK CONSTRAINT [FK_ProductModelProductDescriptionCulture_ProductDescription_ProductDescriptionID]
  GO

  ALTER TABLE [Production].[ProductModelProductDescriptionCulture]  WITH CHECK ADD  CONSTRAINT [FK_ProductModelProductDescriptionCulture_ProductModel_ProductModelID] FOREIGN KEY([ProductModelID])
  REFERENCES [Production].[ProductModel] ([ProductModelID])
  GO

  ALTER TABLE [Production].[ProductModelProductDescriptionCulture] CHECK CONSTRAINT [FK_ProductModelProductDescriptionCulture_ProductModel_ProductModelID]
  GO

