### YamlMime:DocDB
type: Table
id: table.productproductphoto.productproductphoto
description: Cross-reference table mapping products and product photos.
createdAt: 2023-05-08T12:07:29.5230000
lastModifiedAt: 2023-05-08T12:07:38.8270000
name: ProductProductPhoto.ProductProductPhoto
foreignKeys:
- type: ForeignKey
  id: table.productproductphoto.productproductphoto.foreignkey.fk_productproductphoto_product_productid
  description: Foreign key constraint referencing Product.ProductID.
  createdAt: 0001-01-01T00:00:00.0000000
  lastModifiedAt: 0001-01-01T00:00:00.0000000
  name: FK_ProductProductPhoto_Product_ProductID
  columns:
  - name: ProductID
    id: table.productproductphoto.productproductphoto.column.productid
    type: TableColumnRef
  isChecked: true
  referencedKey: PK_Product_ProductID
  referencedTable:
    name: '[Product].[Product]'
    id: table.product.product
    type: TableRef
  deleteAction: 
  updateAction: 
  script: ""
- type: ForeignKey
  id: table.productproductphoto.productproductphoto.foreignkey.fk_productproductphoto_productphoto_productphotoid
  description: Foreign key constraint referencing ProductPhoto.ProductPhotoID.
  createdAt: 0001-01-01T00:00:00.0000000
  lastModifiedAt: 0001-01-01T00:00:00.0000000
  name: FK_ProductProductPhoto_ProductPhoto_ProductPhotoID
  columns:
  - name: ProductPhotoID
    id: table.productproductphoto.productproductphoto.column.productphotoid
    type: TableColumnRef
  isChecked: true
  referencedKey: PK_ProductPhoto_ProductPhotoID
  referencedTable:
    name: '[ProductPhoto].[ProductPhoto]'
    id: table.productphoto.productphoto
    type: TableRef
  deleteAction: 
  updateAction: 
  script: ""
checks: []
partitionInfo:
  isPartitioned: false
  columns: []
  partitionScheme: 
  fileGroup: 
indexes: []
triggers: []
columns:
- type: TableColumn
  id: table.productproductphoto.productproductphoto.column.productid
  description: Product identification number. Foreign key to Product.ProductID.
  createdAt: 0001-01-01T00:00:00.0000000
  lastModifiedAt: 0001-01-01T00:00:00.0000000
  name: ProductID
  dataType: INT
  maxLengthBytes: 4
  precision: 10
  scale: 0
  isNullable: false
  isComputed: false
  computedText: ''
  isIdentity: false
  identityIncrement: 0
  identitySeed: 0
  inPrimaryKey: true
  isForeignKey: true
  foreignKeys:
  - name: FK_ProductProductPhoto_Product_ProductID
    id: table.productproductphoto.productproductphoto.foreignkey.fk_productproductphoto_product_productid
    type: ForeignKeyRef
  default: 
  collation: ''
  isFileStream: false
  isFullTextIndexed: false
  script: ""
- type: TableColumn
  id: table.productproductphoto.productproductphoto.column.productphotoid
  description: Product photo identification number. Foreign key to ProductPhoto.ProductPhotoID.
  createdAt: 0001-01-01T00:00:00.0000000
  lastModifiedAt: 0001-01-01T00:00:00.0000000
  name: ProductPhotoID
  dataType: INT
  maxLengthBytes: 4
  precision: 10
  scale: 0
  isNullable: false
  isComputed: false
  computedText: ''
  isIdentity: false
  identityIncrement: 0
  identitySeed: 0
  inPrimaryKey: true
  isForeignKey: true
  foreignKeys:
  - name: FK_ProductProductPhoto_ProductPhoto_ProductPhotoID
    id: table.productproductphoto.productproductphoto.foreignkey.fk_productproductphoto_productphoto_productphotoid
    type: ForeignKeyRef
  default: 
  collation: ''
  isFileStream: false
  isFullTextIndexed: false
  script: ""
- type: TableColumn
  id: table.productproductphoto.productproductphoto.column.primary
  description: 0 = Photo is not the principal image. 1 = Photo is the principal image.
  createdAt: 0001-01-01T00:00:00.0000000
  lastModifiedAt: 0001-01-01T00:00:00.0000000
  name: Primary
  dataType: FLAG
  maxLengthBytes: 1
  precision: 1
  scale: 0
  isNullable: false
  isComputed: false
  computedText: ''
  isIdentity: false
  identityIncrement: 0
  identitySeed: 0
  inPrimaryKey: false
  isForeignKey: false
  foreignKeys: []
  default: ((0))
  collation: ''
  isFileStream: false
  isFullTextIndexed: false
  script: ""
- type: TableColumn
  id: table.productproductphoto.productproductphoto.column.modifieddate
  description: Date and time the record was last updated.
  createdAt: 0001-01-01T00:00:00.0000000
  lastModifiedAt: 0001-01-01T00:00:00.0000000
  name: ModifiedDate
  dataType: DATETIME
  maxLengthBytes: 8
  precision: 23
  scale: 3
  isNullable: false
  isComputed: false
  computedText: ''
  isIdentity: false
  identityIncrement: 0
  identitySeed: 0
  inPrimaryKey: false
  isForeignKey: false
  foreignKeys: []
  default: (getdate())
  collation: ''
  isFileStream: false
  isFullTextIndexed: false
  script: ""
script: |+
  SET ANSI_NULLS ON
  GO

  SET QUOTED_IDENTIFIER ON
  GO

  CREATE TABLE [Production].[ProductProductPhoto](
  	[ProductID] [int] NOT NULL,
  	[ProductPhotoID] [int] NOT NULL,
  	[Primary] [dbo].[Flag] NOT NULL,
  	[ModifiedDate] [datetime] NOT NULL,
   CONSTRAINT [PK_ProductProductPhoto_ProductID_ProductPhotoID] PRIMARY KEY NONCLUSTERED
  (
  	[ProductID] ASC,
  	[ProductPhotoID] ASC
  )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
  ) ON [PRIMARY]

  GO

  ALTER TABLE [Production].[ProductProductPhoto] ADD  CONSTRAINT [DF_ProductProductPhoto_Primary]  DEFAULT ((0)) FOR [Primary]
  GO

  ALTER TABLE [Production].[ProductProductPhoto] ADD  CONSTRAINT [DF_ProductProductPhoto_ModifiedDate]  DEFAULT (getdate()) FOR [ModifiedDate]
  GO

  ALTER TABLE [Production].[ProductProductPhoto]  WITH CHECK ADD  CONSTRAINT [FK_ProductProductPhoto_Product_ProductID] FOREIGN KEY([ProductID])
  REFERENCES [Production].[Product] ([ProductID])
  GO

  ALTER TABLE [Production].[ProductProductPhoto] CHECK CONSTRAINT [FK_ProductProductPhoto_Product_ProductID]
  GO

  ALTER TABLE [Production].[ProductProductPhoto]  WITH CHECK ADD  CONSTRAINT [FK_ProductProductPhoto_ProductPhoto_ProductPhotoID] FOREIGN KEY([ProductPhotoID])
  REFERENCES [Production].[ProductPhoto] ([ProductPhotoID])
  GO

  ALTER TABLE [Production].[ProductProductPhoto] CHECK CONSTRAINT [FK_ProductProductPhoto_ProductPhoto_ProductPhotoID]
  GO

