### YamlMime:DocDB
type: Table
id: table.sales.currencyrate
description: Currency exchange rates.
name: Sales.CurrencyRate
foreignKeys:
- type: ForeignKey
  id: table.sales.currencyrate.foreignkey.fk_currencyrate_currency_fromcurrencycode
  description: Foreign key constraint referencing Currency.FromCurrencyCode.
  name: FK_CurrencyRate_Currency_FromCurrencyCode
  columns:
  - name: FromCurrencyCode
    id: table.sales.currencyrate.column.fromcurrencycode
    type: TableColumnRef
  isChecked: true
  referencedKey: PK_Currency_CurrencyCode
  referencedTable:
    name: '[Sales].[Currency]'
    id: table.sales.currency
    type: TableRef
  deleteAction: 
  updateAction: 
  databaseId: database.adventureworks2022
  script: ""
- type: ForeignKey
  id: table.sales.currencyrate.foreignkey.fk_currencyrate_currency_tocurrencycode
  description: Foreign key constraint referencing Currency.ToCurrencyCode.
  name: FK_CurrencyRate_Currency_ToCurrencyCode
  columns:
  - name: ToCurrencyCode
    id: table.sales.currencyrate.column.tocurrencycode
    type: TableColumnRef
  isChecked: true
  referencedKey: PK_Currency_CurrencyCode
  referencedTable:
    name: '[Sales].[Currency]'
    id: table.sales.currency
    type: TableRef
  deleteAction: 
  updateAction: 
  databaseId: database.adventureworks2022
  script: ""
checks: []
fileGroup:
  name: '[PRIMARY]'
  id: filegroup.primary
  type: FileGroupRef
fileStreamGroup: 
textFileGroup: 
partitionInfo:
  isPartitioned: false
  columns: []
  partitionScheme: 
fileTableInfo:
  isFileTable: false
  directoryName: 
  nameColumnCollation: 
  namespaceEnabled: false
indexes:
- type: Index
  id: table.sales.currencyrate.index.ak_currencyrate_currencyratedate_fromcurrencycode_tocurrencycode
  description: Unique nonclustered index.
  name: AK_CurrencyRate_CurrencyRateDate_FromCurrencyCode_ToCurrencyCode
  indexType: NONCLUSTERED
  indexKeyType: ''
  isDisabled: false
  isUnique: true
  isClustered: false
  filter: ''
  columns:
  - type: IndexColumn
    id: table.sales.currencyrate.index.ak_currencyrate_currencyratedate_fromcurrencycode_tocurrencycode.indexedcolumn.currencyratedate
    description: 
    name: CurrencyRateDate
    columnRef:
      name: CurrencyRateDate
      id: table.sales.currencyrate.column.currencyratedate
      type: TableColumnRef
    isDescending: false
    isIncluded: false
    columnStoreOrderOrdinal: 0
    databaseId: database.adventureworks2022
    script: ""
  - type: IndexColumn
    id: table.sales.currencyrate.index.ak_currencyrate_currencyratedate_fromcurrencycode_tocurrencycode.indexedcolumn.fromcurrencycode
    description: 
    name: FromCurrencyCode
    columnRef:
      name: FromCurrencyCode
      id: table.sales.currencyrate.column.fromcurrencycode
      type: TableColumnRef
    isDescending: false
    isIncluded: false
    columnStoreOrderOrdinal: 0
    databaseId: database.adventureworks2022
    script: ""
  - type: IndexColumn
    id: table.sales.currencyrate.index.ak_currencyrate_currencyratedate_fromcurrencycode_tocurrencycode.indexedcolumn.tocurrencycode
    description: 
    name: ToCurrencyCode
    columnRef:
      name: ToCurrencyCode
      id: table.sales.currencyrate.column.tocurrencycode
      type: TableColumnRef
    isDescending: false
    isIncluded: false
    columnStoreOrderOrdinal: 0
    databaseId: database.adventureworks2022
    script: ""
  isPartitioned: false
  fileGroup:
    name: PRIMARY
    id: filegroup.primary
    type: FileGroupRef
  fileStreamGroup: 
  options:
  - name: general
    entries:
    - name: autoRecomputeStatistics
      value: true
      type: bool
    - name: ignoreDuplicateKeys
      value: false
      type: bool
  - name: storage
    entries:
    - name: sortInTempdb
      value: 
      type: 
    - name: fillFactor
      value: 0
      type: string
    - name: padIndex
      value: false
      type: bool
  - name: operation
    entries:
    - name: maximumDegreeOfParallelism
      value: 
      type: 
    - name: isOptimizedForSequentialKey
      value: false
      type: bool
  - name: locks
    entries:
    - name: allowPageLocks
      value: true
      type: bool
    - name: allowRowLocks
      value: true
      type: bool
  - name: spatial
    entries:
    - name: isSpatialIndex
      value: false
      type: bool
  - name: xml
    entries:
    - name: isXmlIndex
      value: false
      type: bool
  - name: miscellaneous
    entries:
    - name: hasCompressedPartitions
      value: false
      type: bool
    - name: hasXmlCompressedPartitions
      value: false
      type: bool
    - name: compressAllRowGroups
      value: 
      type: 
    - name: compactLargeObjects
      value: 
      type: 
    - name: compressionDelay
      value: 
      type: 
    - name: dropExistingIndex
      value: 
      type: 
    - name: hasSparseColumn
      value: false
      type: bool
    - name: isFileTableDefined
      value: false
      type: bool
    - name: isFullTextKey
      value: false
      type: bool
    - name: isIndexOnComputed
      value: 
      type: 
    - name: isIndexOnTable
      value: 
      type: 
    - name: isMemoryOptimized
      value: false
      type: bool
    - name: isOnlineRebuildSupported
      value: 
      type: 
    - name: isOptimizedForSequentialKey
      value: false
      type: bool
    - name: lowPriorityAbortAfterWait
      value: 
      type: 
    - name: lowPriorityMaxDuration
      value: 
      type: 
    - name: lowPriorityMaxDuration
      value: 
      type: 
    - name: onlineIndexOperation
      value: 
      type: 
    - name: resumableIndexOperation
      value: 
      type: 
    - name: resumableMaxDuration
      value: 
      type: 
    - name: resumableOperationState
      value: None
      type: enum
  databaseId: database.adventureworks2022
  script: ""
- type: Index
  id: table.sales.currencyrate.index.pk_currencyrate_currencyrateid
  description: Primary key (clustered) constraint
  name: PK_CurrencyRate_CurrencyRateID
  indexType: CLUSTERED
  indexKeyType: PRIMARY
  isDisabled: false
  isUnique: true
  isClustered: true
  filter: ''
  columns:
  - type: IndexColumn
    id: table.sales.currencyrate.index.pk_currencyrate_currencyrateid.indexedcolumn.currencyrateid
    description: 
    name: CurrencyRateID
    columnRef:
      name: CurrencyRateID
      id: table.sales.currencyrate.column.currencyrateid
      type: TableColumnRef
    isDescending: false
    isIncluded: false
    columnStoreOrderOrdinal: 0
    databaseId: database.adventureworks2022
    script: ""
  isPartitioned: false
  fileGroup:
    name: PRIMARY
    id: filegroup.primary
    type: FileGroupRef
  fileStreamGroup: 
  options:
  - name: general
    entries:
    - name: autoRecomputeStatistics
      value: true
      type: bool
    - name: ignoreDuplicateKeys
      value: false
      type: bool
  - name: storage
    entries:
    - name: sortInTempdb
      value: 
      type: 
    - name: fillFactor
      value: 0
      type: string
    - name: padIndex
      value: false
      type: bool
  - name: operation
    entries:
    - name: maximumDegreeOfParallelism
      value: 
      type: 
    - name: isOptimizedForSequentialKey
      value: false
      type: bool
  - name: locks
    entries:
    - name: allowPageLocks
      value: true
      type: bool
    - name: allowRowLocks
      value: true
      type: bool
  - name: spatial
    entries:
    - name: isSpatialIndex
      value: false
      type: bool
  - name: xml
    entries:
    - name: isXmlIndex
      value: false
      type: bool
  - name: miscellaneous
    entries:
    - name: hasCompressedPartitions
      value: false
      type: bool
    - name: hasXmlCompressedPartitions
      value: false
      type: bool
    - name: compressAllRowGroups
      value: 
      type: 
    - name: compactLargeObjects
      value: 
      type: 
    - name: compressionDelay
      value: 
      type: 
    - name: dropExistingIndex
      value: 
      type: 
    - name: hasSparseColumn
      value: false
      type: bool
    - name: isFileTableDefined
      value: false
      type: bool
    - name: isFullTextKey
      value: false
      type: bool
    - name: isIndexOnComputed
      value: 
      type: 
    - name: isIndexOnTable
      value: 
      type: 
    - name: isMemoryOptimized
      value: false
      type: bool
    - name: isOnlineRebuildSupported
      value: 
      type: 
    - name: isOptimizedForSequentialKey
      value: false
      type: bool
    - name: lowPriorityAbortAfterWait
      value: 
      type: 
    - name: lowPriorityMaxDuration
      value: 
      type: 
    - name: lowPriorityMaxDuration
      value: 
      type: 
    - name: onlineIndexOperation
      value: 
      type: 
    - name: resumableIndexOperation
      value: 
      type: 
    - name: resumableMaxDuration
      value: 
      type: 
    - name: resumableOperationState
      value: None
      type: enum
  databaseId: database.adventureworks2022
  script: ""
triggers: []
columns:
- type: TableColumn
  id: table.sales.currencyrate.column.currencyrateid
  description: Primary key for CurrencyRate records.
  name: CurrencyRateID
  dataType: INT
  dataTypeRef: 
  maxLengthBytes: 4
  precision: 10
  scale: 0
  isNullable: false
  isComputed: false
  computedText: ''
  isIdentity: true
  identityIncrement: 1
  identitySeed: 1
  inPrimaryKey: true
  isForeignKey: false
  foreignKeys: []
  default: 
  collation: ''
  isFileStream: false
  isFullTextIndexed: false
  databaseId: database.adventureworks2022
  script: ""
- type: TableColumn
  id: table.sales.currencyrate.column.currencyratedate
  description: Date and time the exchange rate was obtained.
  name: CurrencyRateDate
  dataType: DATETIME
  dataTypeRef: 
  maxLengthBytes: 8
  precision: 23
  scale: 3
  isNullable: false
  isComputed: false
  computedText: ''
  isIdentity: false
  identityIncrement: 0
  identitySeed: 0
  inPrimaryKey: false
  isForeignKey: false
  foreignKeys: []
  default: 
  collation: ''
  isFileStream: false
  isFullTextIndexed: false
  databaseId: database.adventureworks2022
  script: ""
- type: TableColumn
  id: table.sales.currencyrate.column.fromcurrencycode
  description: Exchange rate was converted from this currency code.
  name: FromCurrencyCode
  dataType: NCHAR(3)
  dataTypeRef: 
  maxLengthBytes: 3
  precision: 0
  scale: 0
  isNullable: false
  isComputed: false
  computedText: ''
  isIdentity: false
  identityIncrement: 0
  identitySeed: 0
  inPrimaryKey: false
  isForeignKey: true
  foreignKeys:
  - name: FK_CurrencyRate_Currency_FromCurrencyCode
    id: table.sales.currencyrate.foreignkey.fk_currencyrate_currency_fromcurrencycode
    type: ForeignKeyRef
  default: 
  collation: SQL_Latin1_General_CP1_CI_AS
  isFileStream: false
  isFullTextIndexed: false
  databaseId: database.adventureworks2022
  script: ""
- type: TableColumn
  id: table.sales.currencyrate.column.tocurrencycode
  description: Exchange rate was converted to this currency code.
  name: ToCurrencyCode
  dataType: NCHAR(3)
  dataTypeRef: 
  maxLengthBytes: 3
  precision: 0
  scale: 0
  isNullable: false
  isComputed: false
  computedText: ''
  isIdentity: false
  identityIncrement: 0
  identitySeed: 0
  inPrimaryKey: false
  isForeignKey: true
  foreignKeys:
  - name: FK_CurrencyRate_Currency_ToCurrencyCode
    id: table.sales.currencyrate.foreignkey.fk_currencyrate_currency_tocurrencycode
    type: ForeignKeyRef
  default: 
  collation: SQL_Latin1_General_CP1_CI_AS
  isFileStream: false
  isFullTextIndexed: false
  databaseId: database.adventureworks2022
  script: ""
- type: TableColumn
  id: table.sales.currencyrate.column.averagerate
  description: Average exchange rate for the day.
  name: AverageRate
  dataType: MONEY
  dataTypeRef: 
  maxLengthBytes: 8
  precision: 19
  scale: 4
  isNullable: false
  isComputed: false
  computedText: ''
  isIdentity: false
  identityIncrement: 0
  identitySeed: 0
  inPrimaryKey: false
  isForeignKey: false
  foreignKeys: []
  default: 
  collation: ''
  isFileStream: false
  isFullTextIndexed: false
  databaseId: database.adventureworks2022
  script: ""
- type: TableColumn
  id: table.sales.currencyrate.column.endofdayrate
  description: Final exchange rate for the day.
  name: EndOfDayRate
  dataType: MONEY
  dataTypeRef: 
  maxLengthBytes: 8
  precision: 19
  scale: 4
  isNullable: false
  isComputed: false
  computedText: ''
  isIdentity: false
  identityIncrement: 0
  identitySeed: 0
  inPrimaryKey: false
  isForeignKey: false
  foreignKeys: []
  default: 
  collation: ''
  isFileStream: false
  isFullTextIndexed: false
  databaseId: database.adventureworks2022
  script: ""
- type: TableColumn
  id: table.sales.currencyrate.column.modifieddate
  description: Date and time the record was last updated.
  name: ModifiedDate
  dataType: DATETIME
  dataTypeRef: 
  maxLengthBytes: 8
  precision: 23
  scale: 3
  isNullable: false
  isComputed: false
  computedText: ''
  isIdentity: false
  identityIncrement: 0
  identitySeed: 0
  inPrimaryKey: false
  isForeignKey: false
  foreignKeys: []
  default: (getdate())
  collation: ''
  isFileStream: false
  isFullTextIndexed: false
  databaseId: database.adventureworks2022
  script: ""
databaseId: database.adventureworks2022
script: |+
  SET ANSI_NULLS ON
  GO

  SET QUOTED_IDENTIFIER ON
  GO

  CREATE TABLE [Sales].[CurrencyRate](
  	[CurrencyRateID] [int] IDENTITY(1,1) NOT NULL,
  	[CurrencyRateDate] [datetime] NOT NULL,
  	[FromCurrencyCode] [nchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
  	[ToCurrencyCode] [nchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
  	[AverageRate] [money] NOT NULL,
  	[EndOfDayRate] [money] NOT NULL,
  	[ModifiedDate] [datetime] NOT NULL,
   CONSTRAINT [PK_CurrencyRate_CurrencyRateID] PRIMARY KEY CLUSTERED
  (
  	[CurrencyRateID] ASC
  )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
  ) ON [PRIMARY]

  GO

  SET ANSI_PADDING ON
  GO

  CREATE UNIQUE NONCLUSTERED INDEX [AK_CurrencyRate_CurrencyRateDate_FromCurrencyCode_ToCurrencyCode] ON [Sales].[CurrencyRate]
  (
  	[CurrencyRateDate] ASC,
  	[FromCurrencyCode] ASC,
  	[ToCurrencyCode] ASC
  )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
  GO

  ALTER TABLE [Sales].[CurrencyRate] ADD  CONSTRAINT [DF_CurrencyRate_ModifiedDate]  DEFAULT (getdate()) FOR [ModifiedDate]
  GO

  ALTER TABLE [Sales].[CurrencyRate]  WITH CHECK ADD  CONSTRAINT [FK_CurrencyRate_Currency_FromCurrencyCode] FOREIGN KEY([FromCurrencyCode])
  REFERENCES [Sales].[Currency] ([CurrencyCode])
  GO

  ALTER TABLE [Sales].[CurrencyRate] CHECK CONSTRAINT [FK_CurrencyRate_Currency_FromCurrencyCode]
  GO

  ALTER TABLE [Sales].[CurrencyRate]  WITH CHECK ADD  CONSTRAINT [FK_CurrencyRate_Currency_ToCurrencyCode] FOREIGN KEY([ToCurrencyCode])
  REFERENCES [Sales].[Currency] ([CurrencyCode])
  GO

  ALTER TABLE [Sales].[CurrencyRate] CHECK CONSTRAINT [FK_CurrencyRate_Currency_ToCurrencyCode]
  GO

