### YamlMime:DocDB
type: Table
id: table.sales.specialofferproduct
description: Cross-reference table mapping products to special offer discounts.
createdAt: 2023-05-08T12:07:29.6030000
lastModifiedAt: 2023-05-08T12:07:39.2630000
name: Sales.SpecialOfferProduct
foreignKeys:
- type: ForeignKey
  id: table.sales.specialofferproduct.foreignkey.fk_specialofferproduct_product_productid
  description: Foreign key constraint referencing Product.ProductID.
  createdAt: 0001-01-01T00:00:00.0000000
  lastModifiedAt: 0001-01-01T00:00:00.0000000
  name: FK_SpecialOfferProduct_Product_ProductID
  columns:
  - name: ProductID
    id: table.sales.specialofferproduct.column.productid
    type: TableColumnRef
  isChecked: true
  referencedKey: PK_Product_ProductID
  referencedTable:
    name: '[Production].[Product]'
    id: table.production.product
    type: TableRef
  deleteAction: 
  updateAction: 
  databaseId: database.adventureworks2022
  script: ""
- type: ForeignKey
  id: table.sales.specialofferproduct.foreignkey.fk_specialofferproduct_specialoffer_specialofferid
  description: Foreign key constraint referencing SpecialOffer.SpecialOfferID.
  createdAt: 0001-01-01T00:00:00.0000000
  lastModifiedAt: 0001-01-01T00:00:00.0000000
  name: FK_SpecialOfferProduct_SpecialOffer_SpecialOfferID
  columns:
  - name: SpecialOfferID
    id: table.sales.specialofferproduct.column.specialofferid
    type: TableColumnRef
  isChecked: true
  referencedKey: PK_SpecialOffer_SpecialOfferID
  referencedTable:
    name: '[Sales].[SpecialOffer]'
    id: table.sales.specialoffer
    type: TableRef
  deleteAction: 
  updateAction: 
  databaseId: database.adventureworks2022
  script: ""
checks: []
fileGroup:
  name: '[PRIMARY]'
  id: filegroup.primary
  type: FileGroupRef
fileStreamGroup: 
textFileGroup: 
partitionInfo:
  isPartitioned: false
  columns: []
  partitionScheme: 
  fileGroup: 
fileTableInfo:
  isFileTable: false
  directoryName: 
  nameColumnCollation: 
  namespaceEnabled: false
indexes:
- type: Index
  id: table.sales.specialofferproduct.index.ak_specialofferproduct_rowguid
  description: Unique nonclustered index. Used to support replication samples.
  createdAt: 0001-01-01T00:00:00.0000000
  lastModifiedAt: 0001-01-01T00:00:00.0000000
  name: AK_SpecialOfferProduct_rowguid
  indexType: NONCLUSTERED
  indexKeyType: ''
  isDisabled: false
  isUnique: true
  isClustered: false
  filter: ''
  columns:
  - type: IndexColumn
    id: table.sales.specialofferproduct.index.ak_specialofferproduct_rowguid.indexedcolumn.rowguid
    description: 
    createdAt: 0001-01-01T00:00:00.0000000
    lastModifiedAt: 0001-01-01T00:00:00.0000000
    name: rowguid
    columnRef:
      name: rowguid
      id: table.sales.specialofferproduct.column.rowguid
      type: TableColumnRef
    isDescending: false
    isIncluded: false
    columnStoreOrderOrdinal: 0
    databaseId: database.adventureworks2022
    script: ""
  isPartitioned: false
  fileGroup:
    name: PRIMARY
    id: filegroup.primary
    type: FileGroupRef
  fileStreamGroup: 
  options:
  - name: general
    entries:
    - name: autoRecomputeStatistics
      value: true
      type: bool
    - name: ignoreDuplicateKeys
      value: false
      type: bool
  - name: storage
    entries:
    - name: sortInTempdb
      value: 
      type: 
    - name: fillFactor
      value: 0
      type: string
    - name: padIndex
      value: false
      type: bool
  - name: operation
    entries:
    - name: maximumDegreeOfParallelism
      value: 
      type: 
    - name: isOptimizedForSequentialKey
      value: false
      type: bool
  - name: locks
    entries:
    - name: allowPageLocks
      value: true
      type: bool
    - name: allowRowLocks
      value: true
      type: bool
  - name: spatial
    entries:
    - name: isSpatialIndex
      value: false
      type: bool
  - name: xml
    entries:
    - name: isXmlIndex
      value: false
      type: bool
  - name: miscellaneous
    entries:
    - name: hasCompressedPartitions
      value: false
      type: bool
    - name: hasXmlCompressedPartitions
      value: false
      type: bool
    - name: compressAllRowGroups
      value: 
      type: 
    - name: compactLargeObjects
      value: 
      type: 
    - name: compressionDelay
      value: 
      type: 
    - name: dropExistingIndex
      value: 
      type: 
    - name: hasSparseColumn
      value: false
      type: bool
    - name: isFileTableDefined
      value: false
      type: bool
    - name: isFullTextKey
      value: false
      type: bool
    - name: isIndexOnComputed
      value: 
      type: 
    - name: isIndexOnTable
      value: 
      type: 
    - name: isMemoryOptimized
      value: false
      type: bool
    - name: isOnlineRebuildSupported
      value: 
      type: 
    - name: isOptimizedForSequentialKey
      value: false
      type: bool
    - name: lowPriorityAbortAfterWait
      value: 
      type: 
    - name: lowPriorityMaxDuration
      value: 
      type: 
    - name: lowPriorityMaxDuration
      value: 
      type: 
    - name: onlineIndexOperation
      value: 
      type: 
    - name: resumableIndexOperation
      value: 
      type: 
    - name: resumableMaxDuration
      value: 
      type: 
    - name: resumableOperationState
      value: None
      type: enum
  databaseId: database.adventureworks2022
  script: ""
- type: Index
  id: table.sales.specialofferproduct.index.ix_specialofferproduct_productid
  description: Nonclustered index.
  createdAt: 0001-01-01T00:00:00.0000000
  lastModifiedAt: 0001-01-01T00:00:00.0000000
  name: IX_SpecialOfferProduct_ProductID
  indexType: NONCLUSTERED
  indexKeyType: ''
  isDisabled: false
  isUnique: false
  isClustered: false
  filter: ''
  columns:
  - type: IndexColumn
    id: table.sales.specialofferproduct.index.ix_specialofferproduct_productid.indexedcolumn.productid
    description: 
    createdAt: 0001-01-01T00:00:00.0000000
    lastModifiedAt: 0001-01-01T00:00:00.0000000
    name: ProductID
    columnRef:
      name: ProductID
      id: table.sales.specialofferproduct.column.productid
      type: TableColumnRef
    isDescending: false
    isIncluded: false
    columnStoreOrderOrdinal: 0
    databaseId: database.adventureworks2022
    script: ""
  isPartitioned: false
  fileGroup:
    name: PRIMARY
    id: filegroup.primary
    type: FileGroupRef
  fileStreamGroup: 
  options:
  - name: general
    entries:
    - name: autoRecomputeStatistics
      value: true
      type: bool
    - name: ignoreDuplicateKeys
      value: false
      type: bool
  - name: storage
    entries:
    - name: sortInTempdb
      value: 
      type: 
    - name: fillFactor
      value: 0
      type: string
    - name: padIndex
      value: false
      type: bool
  - name: operation
    entries:
    - name: maximumDegreeOfParallelism
      value: 
      type: 
    - name: isOptimizedForSequentialKey
      value: false
      type: bool
  - name: locks
    entries:
    - name: allowPageLocks
      value: true
      type: bool
    - name: allowRowLocks
      value: true
      type: bool
  - name: spatial
    entries:
    - name: isSpatialIndex
      value: false
      type: bool
  - name: xml
    entries:
    - name: isXmlIndex
      value: false
      type: bool
  - name: miscellaneous
    entries:
    - name: hasCompressedPartitions
      value: false
      type: bool
    - name: hasXmlCompressedPartitions
      value: false
      type: bool
    - name: compressAllRowGroups
      value: 
      type: 
    - name: compactLargeObjects
      value: 
      type: 
    - name: compressionDelay
      value: 
      type: 
    - name: dropExistingIndex
      value: 
      type: 
    - name: hasSparseColumn
      value: false
      type: bool
    - name: isFileTableDefined
      value: false
      type: bool
    - name: isFullTextKey
      value: false
      type: bool
    - name: isIndexOnComputed
      value: 
      type: 
    - name: isIndexOnTable
      value: 
      type: 
    - name: isMemoryOptimized
      value: false
      type: bool
    - name: isOnlineRebuildSupported
      value: 
      type: 
    - name: isOptimizedForSequentialKey
      value: false
      type: bool
    - name: lowPriorityAbortAfterWait
      value: 
      type: 
    - name: lowPriorityMaxDuration
      value: 
      type: 
    - name: lowPriorityMaxDuration
      value: 
      type: 
    - name: onlineIndexOperation
      value: 
      type: 
    - name: resumableIndexOperation
      value: 
      type: 
    - name: resumableMaxDuration
      value: 
      type: 
    - name: resumableOperationState
      value: None
      type: enum
  databaseId: database.adventureworks2022
  script: ""
- type: Index
  id: table.sales.specialofferproduct.index.pk_specialofferproduct_specialofferid_productid
  description: Primary key (clustered) constraint
  createdAt: 0001-01-01T00:00:00.0000000
  lastModifiedAt: 0001-01-01T00:00:00.0000000
  name: PK_SpecialOfferProduct_SpecialOfferID_ProductID
  indexType: CLUSTERED
  indexKeyType: PRIMARY
  isDisabled: false
  isUnique: true
  isClustered: true
  filter: ''
  columns:
  - type: IndexColumn
    id: table.sales.specialofferproduct.index.pk_specialofferproduct_specialofferid_productid.indexedcolumn.specialofferid
    description: 
    createdAt: 0001-01-01T00:00:00.0000000
    lastModifiedAt: 0001-01-01T00:00:00.0000000
    name: SpecialOfferID
    columnRef:
      name: SpecialOfferID
      id: table.sales.specialofferproduct.column.specialofferid
      type: TableColumnRef
    isDescending: false
    isIncluded: false
    columnStoreOrderOrdinal: 0
    databaseId: database.adventureworks2022
    script: ""
  - type: IndexColumn
    id: table.sales.specialofferproduct.index.pk_specialofferproduct_specialofferid_productid.indexedcolumn.productid
    description: 
    createdAt: 0001-01-01T00:00:00.0000000
    lastModifiedAt: 0001-01-01T00:00:00.0000000
    name: ProductID
    columnRef:
      name: ProductID
      id: table.sales.specialofferproduct.column.productid
      type: TableColumnRef
    isDescending: false
    isIncluded: false
    columnStoreOrderOrdinal: 0
    databaseId: database.adventureworks2022
    script: ""
  isPartitioned: false
  fileGroup:
    name: PRIMARY
    id: filegroup.primary
    type: FileGroupRef
  fileStreamGroup: 
  options:
  - name: general
    entries:
    - name: autoRecomputeStatistics
      value: true
      type: bool
    - name: ignoreDuplicateKeys
      value: false
      type: bool
  - name: storage
    entries:
    - name: sortInTempdb
      value: 
      type: 
    - name: fillFactor
      value: 0
      type: string
    - name: padIndex
      value: false
      type: bool
  - name: operation
    entries:
    - name: maximumDegreeOfParallelism
      value: 
      type: 
    - name: isOptimizedForSequentialKey
      value: false
      type: bool
  - name: locks
    entries:
    - name: allowPageLocks
      value: true
      type: bool
    - name: allowRowLocks
      value: true
      type: bool
  - name: spatial
    entries:
    - name: isSpatialIndex
      value: false
      type: bool
  - name: xml
    entries:
    - name: isXmlIndex
      value: false
      type: bool
  - name: miscellaneous
    entries:
    - name: hasCompressedPartitions
      value: false
      type: bool
    - name: hasXmlCompressedPartitions
      value: false
      type: bool
    - name: compressAllRowGroups
      value: 
      type: 
    - name: compactLargeObjects
      value: 
      type: 
    - name: compressionDelay
      value: 
      type: 
    - name: dropExistingIndex
      value: 
      type: 
    - name: hasSparseColumn
      value: false
      type: bool
    - name: isFileTableDefined
      value: false
      type: bool
    - name: isFullTextKey
      value: false
      type: bool
    - name: isIndexOnComputed
      value: 
      type: 
    - name: isIndexOnTable
      value: 
      type: 
    - name: isMemoryOptimized
      value: false
      type: bool
    - name: isOnlineRebuildSupported
      value: 
      type: 
    - name: isOptimizedForSequentialKey
      value: false
      type: bool
    - name: lowPriorityAbortAfterWait
      value: 
      type: 
    - name: lowPriorityMaxDuration
      value: 
      type: 
    - name: lowPriorityMaxDuration
      value: 
      type: 
    - name: onlineIndexOperation
      value: 
      type: 
    - name: resumableIndexOperation
      value: 
      type: 
    - name: resumableMaxDuration
      value: 
      type: 
    - name: resumableOperationState
      value: None
      type: enum
  databaseId: database.adventureworks2022
  script: ""
triggers: []
columns:
- type: TableColumn
  id: table.sales.specialofferproduct.column.specialofferid
  description: Primary key for SpecialOfferProduct records.
  createdAt: 0001-01-01T00:00:00.0000000
  lastModifiedAt: 0001-01-01T00:00:00.0000000
  name: SpecialOfferID
  dataType: INT
  dataTypeRef: 
  maxLengthBytes: 4
  precision: 10
  scale: 0
  isNullable: false
  isComputed: false
  computedText: ''
  isIdentity: false
  identityIncrement: 0
  identitySeed: 0
  inPrimaryKey: true
  isForeignKey: true
  foreignKeys:
  - name: FK_SpecialOfferProduct_SpecialOffer_SpecialOfferID
    id: table.sales.specialofferproduct.foreignkey.fk_specialofferproduct_specialoffer_specialofferid
    type: ForeignKeyRef
  default: 
  collation: ''
  isFileStream: false
  isFullTextIndexed: false
  databaseId: database.adventureworks2022
  script: ""
- type: TableColumn
  id: table.sales.specialofferproduct.column.productid
  description: Product identification number. Foreign key to Product.ProductID.
  createdAt: 0001-01-01T00:00:00.0000000
  lastModifiedAt: 0001-01-01T00:00:00.0000000
  name: ProductID
  dataType: INT
  dataTypeRef: 
  maxLengthBytes: 4
  precision: 10
  scale: 0
  isNullable: false
  isComputed: false
  computedText: ''
  isIdentity: false
  identityIncrement: 0
  identitySeed: 0
  inPrimaryKey: true
  isForeignKey: true
  foreignKeys:
  - name: FK_SpecialOfferProduct_Product_ProductID
    id: table.sales.specialofferproduct.foreignkey.fk_specialofferproduct_product_productid
    type: ForeignKeyRef
  default: 
  collation: ''
  isFileStream: false
  isFullTextIndexed: false
  databaseId: database.adventureworks2022
  script: ""
- type: TableColumn
  id: table.sales.specialofferproduct.column.rowguid
  description: ROWGUIDCOL number uniquely identifying the record. Used to support a merge replication sample.
  createdAt: 0001-01-01T00:00:00.0000000
  lastModifiedAt: 0001-01-01T00:00:00.0000000
  name: rowguid
  dataType: UNIQUEIDENTIFIER
  dataTypeRef: 
  maxLengthBytes: 16
  precision: 0
  scale: 0
  isNullable: false
  isComputed: false
  computedText: ''
  isIdentity: false
  identityIncrement: 0
  identitySeed: 0
  inPrimaryKey: false
  isForeignKey: false
  foreignKeys: []
  default: (newid())
  collation: ''
  isFileStream: false
  isFullTextIndexed: false
  databaseId: database.adventureworks2022
  script: ""
- type: TableColumn
  id: table.sales.specialofferproduct.column.modifieddate
  description: Date and time the record was last updated.
  createdAt: 0001-01-01T00:00:00.0000000
  lastModifiedAt: 0001-01-01T00:00:00.0000000
  name: ModifiedDate
  dataType: DATETIME
  dataTypeRef: 
  maxLengthBytes: 8
  precision: 23
  scale: 3
  isNullable: false
  isComputed: false
  computedText: ''
  isIdentity: false
  identityIncrement: 0
  identitySeed: 0
  inPrimaryKey: false
  isForeignKey: false
  foreignKeys: []
  default: (getdate())
  collation: ''
  isFileStream: false
  isFullTextIndexed: false
  databaseId: database.adventureworks2022
  script: ""
databaseId: database.adventureworks2022
script: |+
  SET ANSI_NULLS ON
  GO

  SET QUOTED_IDENTIFIER ON
  GO

  CREATE TABLE [Sales].[SpecialOfferProduct](
  	[SpecialOfferID] [int] NOT NULL,
  	[ProductID] [int] NOT NULL,
  	[rowguid] [uniqueidentifier] ROWGUIDCOL  NOT NULL,
  	[ModifiedDate] [datetime] NOT NULL,
   CONSTRAINT [PK_SpecialOfferProduct_SpecialOfferID_ProductID] PRIMARY KEY CLUSTERED
  (
  	[SpecialOfferID] ASC,
  	[ProductID] ASC
  )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
  ) ON [PRIMARY]

  GO

  CREATE UNIQUE NONCLUSTERED INDEX [AK_SpecialOfferProduct_rowguid] ON [Sales].[SpecialOfferProduct]
  (
  	[rowguid] ASC
  )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
  GO

  CREATE NONCLUSTERED INDEX [IX_SpecialOfferProduct_ProductID] ON [Sales].[SpecialOfferProduct]
  (
  	[ProductID] ASC
  )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
  GO

  ALTER TABLE [Sales].[SpecialOfferProduct] ADD  CONSTRAINT [DF_SpecialOfferProduct_rowguid]  DEFAULT (newid()) FOR [rowguid]
  GO

  ALTER TABLE [Sales].[SpecialOfferProduct] ADD  CONSTRAINT [DF_SpecialOfferProduct_ModifiedDate]  DEFAULT (getdate()) FOR [ModifiedDate]
  GO

  ALTER TABLE [Sales].[SpecialOfferProduct]  WITH CHECK ADD  CONSTRAINT [FK_SpecialOfferProduct_Product_ProductID] FOREIGN KEY([ProductID])
  REFERENCES [Production].[Product] ([ProductID])
  GO

  ALTER TABLE [Sales].[SpecialOfferProduct] CHECK CONSTRAINT [FK_SpecialOfferProduct_Product_ProductID]
  GO

  ALTER TABLE [Sales].[SpecialOfferProduct]  WITH CHECK ADD  CONSTRAINT [FK_SpecialOfferProduct_SpecialOffer_SpecialOfferID] FOREIGN KEY([SpecialOfferID])
  REFERENCES [Sales].[SpecialOffer] ([SpecialOfferID])
  GO

  ALTER TABLE [Sales].[SpecialOfferProduct] CHECK CONSTRAINT [FK_SpecialOfferProduct_SpecialOffer_SpecialOfferID]
  GO

