### YamlMime:DocDB
type: Table
id: table.sales.personcreditcard
description: 'Cross-reference table mapping people to their credit card information in the CreditCard table. '
createdAt: 2023-05-08T12:07:29.4800000
lastModifiedAt: 2023-05-08T12:07:38.7230000
name: Sales.PersonCreditCard
foreignKeys:
- type: ForeignKey
  id: table.sales.personcreditcard.foreignkey.fk_personcreditcard_creditcard_creditcardid
  description: Foreign key constraint referencing CreditCard.CreditCardID.
  createdAt: 0001-01-01T00:00:00.0000000
  lastModifiedAt: 0001-01-01T00:00:00.0000000
  name: FK_PersonCreditCard_CreditCard_CreditCardID
  columns:
  - name: CreditCardID
    id: table.sales.personcreditcard.column.creditcardid
    type: TableColumnRef
  isChecked: true
  referencedKey: PK_CreditCard_CreditCardID
  referencedTable:
    name: '[Sales].[CreditCard]'
    id: table.sales.creditcard
    type: TableRef
  deleteAction: 
  updateAction: 
  script: |+
    ALTER TABLE [Sales].[PersonCreditCard]  WITH CHECK ADD  CONSTRAINT [FK_PersonCreditCard_CreditCard_CreditCardID] FOREIGN KEY([CreditCardID])
    REFERENCES [Sales].[CreditCard] ([CreditCardID])
    GO

    ALTER TABLE [Sales].[PersonCreditCard] CHECK CONSTRAINT [FK_PersonCreditCard_CreditCard_CreditCardID]
    GO

- type: ForeignKey
  id: table.sales.personcreditcard.foreignkey.fk_personcreditcard_person_businessentityid
  description: Foreign key constraint referencing Person.BusinessEntityID.
  createdAt: 0001-01-01T00:00:00.0000000
  lastModifiedAt: 0001-01-01T00:00:00.0000000
  name: FK_PersonCreditCard_Person_BusinessEntityID
  columns:
  - name: BusinessEntityID
    id: table.sales.personcreditcard.column.businessentityid
    type: TableColumnRef
  isChecked: true
  referencedKey: PK_Person_BusinessEntityID
  referencedTable:
    name: '[Person].[Person]'
    id: table.person.person
    type: TableRef
  deleteAction: 
  updateAction: 
  script: |+
    ALTER TABLE [Sales].[PersonCreditCard]  WITH CHECK ADD  CONSTRAINT [FK_PersonCreditCard_Person_BusinessEntityID] FOREIGN KEY([BusinessEntityID])
    REFERENCES [Person].[Person] ([BusinessEntityID])
    GO

    ALTER TABLE [Sales].[PersonCreditCard] CHECK CONSTRAINT [FK_PersonCreditCard_Person_BusinessEntityID]
    GO

checks: []
partitionInfo:
  isPartitioned: false
  columns: []
  partitionScheme: 
  fileGroup: 
indexes: []
triggers: []
columns:
- type: TableColumn
  id: table.sales.personcreditcard.column.businessentityid
  description: Business entity identification number. Foreign key to Person.BusinessEntityID.
  createdAt: 0001-01-01T00:00:00.0000000
  lastModifiedAt: 0001-01-01T00:00:00.0000000
  name: BusinessEntityID
  dataType: INT
  maxLengthBytes: 4
  precision: 10
  scale: 0
  isNullable: false
  isComputed: false
  computedText: ''
  isIdentity: false
  identityIncrement: 0
  identitySeed: 0
  inPrimaryKey: true
  isForeignKey: true
  foreignKeys:
  - name: FK_PersonCreditCard_Person_BusinessEntityID
    id: table.sales.personcreditcard.foreignkey.fk_personcreditcard_person_businessentityid
    type: ForeignKeyRef
  default: 
  collation: ''
  isFileStream: false
  isFullTextIndexed: false
  script: ""
- type: TableColumn
  id: table.sales.personcreditcard.column.creditcardid
  description: Credit card identification number. Foreign key to CreditCard.CreditCardID.
  createdAt: 0001-01-01T00:00:00.0000000
  lastModifiedAt: 0001-01-01T00:00:00.0000000
  name: CreditCardID
  dataType: INT
  maxLengthBytes: 4
  precision: 10
  scale: 0
  isNullable: false
  isComputed: false
  computedText: ''
  isIdentity: false
  identityIncrement: 0
  identitySeed: 0
  inPrimaryKey: true
  isForeignKey: true
  foreignKeys:
  - name: FK_PersonCreditCard_CreditCard_CreditCardID
    id: table.sales.personcreditcard.foreignkey.fk_personcreditcard_creditcard_creditcardid
    type: ForeignKeyRef
  default: 
  collation: ''
  isFileStream: false
  isFullTextIndexed: false
  script: ""
- type: TableColumn
  id: table.sales.personcreditcard.column.modifieddate
  description: Date and time the record was last updated.
  createdAt: 0001-01-01T00:00:00.0000000
  lastModifiedAt: 0001-01-01T00:00:00.0000000
  name: ModifiedDate
  dataType: DATETIME
  maxLengthBytes: 8
  precision: 23
  scale: 3
  isNullable: false
  isComputed: false
  computedText: ''
  isIdentity: false
  identityIncrement: 0
  identitySeed: 0
  inPrimaryKey: false
  isForeignKey: false
  foreignKeys: []
  default: (getdate())
  collation: ''
  isFileStream: false
  isFullTextIndexed: false
  script: ""
script: |+
  SET ANSI_NULLS ON
  GO

  SET QUOTED_IDENTIFIER ON
  GO

  CREATE TABLE [Sales].[PersonCreditCard](
  	[BusinessEntityID] [int] NOT NULL,
  	[CreditCardID] [int] NOT NULL,
  	[ModifiedDate] [datetime] NOT NULL,
   CONSTRAINT [PK_PersonCreditCard_BusinessEntityID_CreditCardID] PRIMARY KEY CLUSTERED
  (
  	[BusinessEntityID] ASC,
  	[CreditCardID] ASC
  )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
  ) ON [PRIMARY]

  GO

  ALTER TABLE [Sales].[PersonCreditCard] ADD  CONSTRAINT [DF_PersonCreditCard_ModifiedDate]  DEFAULT (getdate()) FOR [ModifiedDate]
  GO

  ALTER TABLE [Sales].[PersonCreditCard]  WITH CHECK ADD  CONSTRAINT [FK_PersonCreditCard_CreditCard_CreditCardID] FOREIGN KEY([CreditCardID])
  REFERENCES [Sales].[CreditCard] ([CreditCardID])
  GO

  ALTER TABLE [Sales].[PersonCreditCard] CHECK CONSTRAINT [FK_PersonCreditCard_CreditCard_CreditCardID]
  GO

  ALTER TABLE [Sales].[PersonCreditCard]  WITH CHECK ADD  CONSTRAINT [FK_PersonCreditCard_Person_BusinessEntityID] FOREIGN KEY([BusinessEntityID])
  REFERENCES [Person].[Person] ([BusinessEntityID])
  GO

  ALTER TABLE [Sales].[PersonCreditCard] CHECK CONSTRAINT [FK_PersonCreditCard_Person_BusinessEntityID]
  GO

