### YamlMime:DocDB
type: View
id: view.sales.vstorewithcontacts
description: Stores (including store contacts) that sell Adventure Works Cycles products to consumers.
name: Sales.vStoreWithContacts
indexes: []
triggers: []
columns:
- type: ViewColumn
  id: view.sales.vstorewithcontacts.column.businessentityid
  description: 
  name: BusinessEntityID
  dataType: INT
  dataTypeRef: 
  maxLengthBytes: 4
  precision: 10
  scale: 0
  isNullable: false
  isComputed: false
  computedText: ''
  isIdentity: false
  identityIncrement: 0
  identitySeed: 0
  inPrimaryKey: false
  isForeignKey: false
  foreignKeys: []
  default: 
  collation: ''
  isFileStream: false
  isFullTextIndexed: false
  databaseId: database.adventureworks2022
  script: ""
- type: ViewColumn
  id: view.sales.vstorewithcontacts.column.name
  description: 
  name: Name
  dataType: '[dbo].[Name]'
  dataTypeRef:
    name: '[dbo].[Name]'
    id: userdefineddatatype.dbo.name
    type: UserDefinedDataTypeRef
  maxLengthBytes: 50
  precision: 0
  scale: 0
  isNullable: false
  isComputed: false
  computedText: ''
  isIdentity: false
  identityIncrement: 0
  identitySeed: 0
  inPrimaryKey: false
  isForeignKey: false
  foreignKeys: []
  default: 
  collation: SQL_Latin1_General_CP1_CI_AS
  isFileStream: false
  isFullTextIndexed: false
  databaseId: database.adventureworks2022
  script: ""
- type: ViewColumn
  id: view.sales.vstorewithcontacts.column.contacttype
  description: 
  name: ContactType
  dataType: '[dbo].[Name]'
  dataTypeRef:
    name: '[dbo].[Name]'
    id: userdefineddatatype.dbo.name
    type: UserDefinedDataTypeRef
  maxLengthBytes: 50
  precision: 0
  scale: 0
  isNullable: false
  isComputed: false
  computedText: ''
  isIdentity: false
  identityIncrement: 0
  identitySeed: 0
  inPrimaryKey: false
  isForeignKey: false
  foreignKeys: []
  default: 
  collation: SQL_Latin1_General_CP1_CI_AS
  isFileStream: false
  isFullTextIndexed: false
  databaseId: database.adventureworks2022
  script: ""
- type: ViewColumn
  id: view.sales.vstorewithcontacts.column.title
  description: 
  name: Title
  dataType: NVARCHAR(8)
  dataTypeRef: 
  maxLengthBytes: 8
  precision: 0
  scale: 0
  isNullable: true
  isComputed: false
  computedText: ''
  isIdentity: false
  identityIncrement: 0
  identitySeed: 0
  inPrimaryKey: false
  isForeignKey: false
  foreignKeys: []
  default: 
  collation: SQL_Latin1_General_CP1_CI_AS
  isFileStream: false
  isFullTextIndexed: false
  databaseId: database.adventureworks2022
  script: ""
- type: ViewColumn
  id: view.sales.vstorewithcontacts.column.firstname
  description: 
  name: FirstName
  dataType: '[dbo].[Name]'
  dataTypeRef:
    name: '[dbo].[Name]'
    id: userdefineddatatype.dbo.name
    type: UserDefinedDataTypeRef
  maxLengthBytes: 50
  precision: 0
  scale: 0
  isNullable: false
  isComputed: false
  computedText: ''
  isIdentity: false
  identityIncrement: 0
  identitySeed: 0
  inPrimaryKey: false
  isForeignKey: false
  foreignKeys: []
  default: 
  collation: SQL_Latin1_General_CP1_CI_AS
  isFileStream: false
  isFullTextIndexed: false
  databaseId: database.adventureworks2022
  script: ""
- type: ViewColumn
  id: view.sales.vstorewithcontacts.column.middlename
  description: 
  name: MiddleName
  dataType: '[dbo].[Name]'
  dataTypeRef:
    name: '[dbo].[Name]'
    id: userdefineddatatype.dbo.name
    type: UserDefinedDataTypeRef
  maxLengthBytes: 50
  precision: 0
  scale: 0
  isNullable: true
  isComputed: false
  computedText: ''
  isIdentity: false
  identityIncrement: 0
  identitySeed: 0
  inPrimaryKey: false
  isForeignKey: false
  foreignKeys: []
  default: 
  collation: SQL_Latin1_General_CP1_CI_AS
  isFileStream: false
  isFullTextIndexed: false
  databaseId: database.adventureworks2022
  script: ""
- type: ViewColumn
  id: view.sales.vstorewithcontacts.column.lastname
  description: 
  name: LastName
  dataType: '[dbo].[Name]'
  dataTypeRef:
    name: '[dbo].[Name]'
    id: userdefineddatatype.dbo.name
    type: UserDefinedDataTypeRef
  maxLengthBytes: 50
  precision: 0
  scale: 0
  isNullable: false
  isComputed: false
  computedText: ''
  isIdentity: false
  identityIncrement: 0
  identitySeed: 0
  inPrimaryKey: false
  isForeignKey: false
  foreignKeys: []
  default: 
  collation: SQL_Latin1_General_CP1_CI_AS
  isFileStream: false
  isFullTextIndexed: false
  databaseId: database.adventureworks2022
  script: ""
- type: ViewColumn
  id: view.sales.vstorewithcontacts.column.suffix
  description: 
  name: Suffix
  dataType: NVARCHAR(10)
  dataTypeRef: 
  maxLengthBytes: 10
  precision: 0
  scale: 0
  isNullable: true
  isComputed: false
  computedText: ''
  isIdentity: false
  identityIncrement: 0
  identitySeed: 0
  inPrimaryKey: false
  isForeignKey: false
  foreignKeys: []
  default: 
  collation: SQL_Latin1_General_CP1_CI_AS
  isFileStream: false
  isFullTextIndexed: false
  databaseId: database.adventureworks2022
  script: ""
- type: ViewColumn
  id: view.sales.vstorewithcontacts.column.phonenumber
  description: 
  name: PhoneNumber
  dataType: '[dbo].[Phone]'
  dataTypeRef:
    name: '[dbo].[Phone]'
    id: userdefineddatatype.dbo.phone
    type: UserDefinedDataTypeRef
  maxLengthBytes: 25
  precision: 0
  scale: 0
  isNullable: true
  isComputed: false
  computedText: ''
  isIdentity: false
  identityIncrement: 0
  identitySeed: 0
  inPrimaryKey: false
  isForeignKey: false
  foreignKeys: []
  default: 
  collation: SQL_Latin1_General_CP1_CI_AS
  isFileStream: false
  isFullTextIndexed: false
  databaseId: database.adventureworks2022
  script: ""
- type: ViewColumn
  id: view.sales.vstorewithcontacts.column.phonenumbertype
  description: 
  name: PhoneNumberType
  dataType: '[dbo].[Name]'
  dataTypeRef:
    name: '[dbo].[Name]'
    id: userdefineddatatype.dbo.name
    type: UserDefinedDataTypeRef
  maxLengthBytes: 50
  precision: 0
  scale: 0
  isNullable: true
  isComputed: false
  computedText: ''
  isIdentity: false
  identityIncrement: 0
  identitySeed: 0
  inPrimaryKey: false
  isForeignKey: false
  foreignKeys: []
  default: 
  collation: SQL_Latin1_General_CP1_CI_AS
  isFileStream: false
  isFullTextIndexed: false
  databaseId: database.adventureworks2022
  script: ""
- type: ViewColumn
  id: view.sales.vstorewithcontacts.column.emailaddress
  description: 
  name: EmailAddress
  dataType: NVARCHAR(50)
  dataTypeRef: 
  maxLengthBytes: 50
  precision: 0
  scale: 0
  isNullable: true
  isComputed: false
  computedText: ''
  isIdentity: false
  identityIncrement: 0
  identitySeed: 0
  inPrimaryKey: false
  isForeignKey: false
  foreignKeys: []
  default: 
  collation: SQL_Latin1_General_CP1_CI_AS
  isFileStream: false
  isFullTextIndexed: false
  databaseId: database.adventureworks2022
  script: ""
- type: ViewColumn
  id: view.sales.vstorewithcontacts.column.emailpromotion
  description: 
  name: EmailPromotion
  dataType: INT
  dataTypeRef: 
  maxLengthBytes: 4
  precision: 10
  scale: 0
  isNullable: false
  isComputed: false
  computedText: ''
  isIdentity: false
  identityIncrement: 0
  identitySeed: 0
  inPrimaryKey: false
  isForeignKey: false
  foreignKeys: []
  default: 
  collation: ''
  isFileStream: false
  isFullTextIndexed: false
  databaseId: database.adventureworks2022
  script: ""
databaseId: database.adventureworks2022
script: |+
  SET ANSI_NULLS ON
  GO

  SET QUOTED_IDENTIFIER ON
  GO

  CREATE VIEW [Sales].[vStoreWithContacts] AS
  SELECT
      s.[BusinessEntityID]
      ,s.[Name]
      ,ct.[Name] AS [ContactType]
      ,p.[Title]
      ,p.[FirstName]
      ,p.[MiddleName]
      ,p.[LastName]
      ,p.[Suffix]
      ,pp.[PhoneNumber]
  	,pnt.[Name] AS [PhoneNumberType]
      ,ea.[EmailAddress]
      ,p.[EmailPromotion]
  FROM [Sales].[Store] s
      INNER JOIN [Person].[BusinessEntityContact] bec
      ON bec.[BusinessEntityID] = s.[BusinessEntityID]
  	INNER JOIN [Person].[ContactType] ct
  	ON ct.[ContactTypeID] = bec.[ContactTypeID]
  	INNER JOIN [Person].[Person] p
  	ON p.[BusinessEntityID] = bec.[PersonID]
  	LEFT OUTER JOIN [Person].[EmailAddress] ea
  	ON ea.[BusinessEntityID] = p.[BusinessEntityID]
  	LEFT OUTER JOIN [Person].[PersonPhone] pp
  	ON pp.[BusinessEntityID] = p.[BusinessEntityID]
  	LEFT OUTER JOIN [Person].[PhoneNumberType] pnt
  	ON pnt.[PhoneNumberTypeID] = pp.[PhoneNumberTypeID];

  GO

