### YamlMime:DocDB
type: View
id: view.sales.vsalesperson
description: Sales representiatives (names and addresses) and their sales-related information.
name: Sales.vSalesPerson
indexes: []
triggers: []
columns:
- type: ViewColumn
  id: view.sales.vsalesperson.column.businessentityid
  description: 
  name: BusinessEntityID
  dataType: INT
  dataTypeRef: 
  maxLengthBytes: 4
  precision: 10
  scale: 0
  isNullable: false
  isComputed: false
  computedText: ''
  isIdentity: false
  identityIncrement: 0
  identitySeed: 0
  inPrimaryKey: false
  isForeignKey: false
  foreignKeys: []
  default: 
  collation: ''
  isFileStream: false
  isFullTextIndexed: false
  databaseId: database.adventureworks2022
  script: ""
- type: ViewColumn
  id: view.sales.vsalesperson.column.title
  description: 
  name: Title
  dataType: NVARCHAR(8)
  dataTypeRef: 
  maxLengthBytes: 8
  precision: 0
  scale: 0
  isNullable: true
  isComputed: false
  computedText: ''
  isIdentity: false
  identityIncrement: 0
  identitySeed: 0
  inPrimaryKey: false
  isForeignKey: false
  foreignKeys: []
  default: 
  collation: SQL_Latin1_General_CP1_CI_AS
  isFileStream: false
  isFullTextIndexed: false
  databaseId: database.adventureworks2022
  script: ""
- type: ViewColumn
  id: view.sales.vsalesperson.column.firstname
  description: 
  name: FirstName
  dataType: '[dbo].[Name]'
  dataTypeRef:
    name: '[dbo].[Name]'
    id: userdefineddatatype.dbo.name
    type: UserDefinedDataTypeRef
  maxLengthBytes: 50
  precision: 0
  scale: 0
  isNullable: false
  isComputed: false
  computedText: ''
  isIdentity: false
  identityIncrement: 0
  identitySeed: 0
  inPrimaryKey: false
  isForeignKey: false
  foreignKeys: []
  default: 
  collation: SQL_Latin1_General_CP1_CI_AS
  isFileStream: false
  isFullTextIndexed: false
  databaseId: database.adventureworks2022
  script: ""
- type: ViewColumn
  id: view.sales.vsalesperson.column.middlename
  description: 
  name: MiddleName
  dataType: '[dbo].[Name]'
  dataTypeRef:
    name: '[dbo].[Name]'
    id: userdefineddatatype.dbo.name
    type: UserDefinedDataTypeRef
  maxLengthBytes: 50
  precision: 0
  scale: 0
  isNullable: true
  isComputed: false
  computedText: ''
  isIdentity: false
  identityIncrement: 0
  identitySeed: 0
  inPrimaryKey: false
  isForeignKey: false
  foreignKeys: []
  default: 
  collation: SQL_Latin1_General_CP1_CI_AS
  isFileStream: false
  isFullTextIndexed: false
  databaseId: database.adventureworks2022
  script: ""
- type: ViewColumn
  id: view.sales.vsalesperson.column.lastname
  description: 
  name: LastName
  dataType: '[dbo].[Name]'
  dataTypeRef:
    name: '[dbo].[Name]'
    id: userdefineddatatype.dbo.name
    type: UserDefinedDataTypeRef
  maxLengthBytes: 50
  precision: 0
  scale: 0
  isNullable: false
  isComputed: false
  computedText: ''
  isIdentity: false
  identityIncrement: 0
  identitySeed: 0
  inPrimaryKey: false
  isForeignKey: false
  foreignKeys: []
  default: 
  collation: SQL_Latin1_General_CP1_CI_AS
  isFileStream: false
  isFullTextIndexed: false
  databaseId: database.adventureworks2022
  script: ""
- type: ViewColumn
  id: view.sales.vsalesperson.column.suffix
  description: 
  name: Suffix
  dataType: NVARCHAR(10)
  dataTypeRef: 
  maxLengthBytes: 10
  precision: 0
  scale: 0
  isNullable: true
  isComputed: false
  computedText: ''
  isIdentity: false
  identityIncrement: 0
  identitySeed: 0
  inPrimaryKey: false
  isForeignKey: false
  foreignKeys: []
  default: 
  collation: SQL_Latin1_General_CP1_CI_AS
  isFileStream: false
  isFullTextIndexed: false
  databaseId: database.adventureworks2022
  script: ""
- type: ViewColumn
  id: view.sales.vsalesperson.column.jobtitle
  description: 
  name: JobTitle
  dataType: NVARCHAR(50)
  dataTypeRef: 
  maxLengthBytes: 50
  precision: 0
  scale: 0
  isNullable: false
  isComputed: false
  computedText: ''
  isIdentity: false
  identityIncrement: 0
  identitySeed: 0
  inPrimaryKey: false
  isForeignKey: false
  foreignKeys: []
  default: 
  collation: SQL_Latin1_General_CP1_CI_AS
  isFileStream: false
  isFullTextIndexed: false
  databaseId: database.adventureworks2022
  script: ""
- type: ViewColumn
  id: view.sales.vsalesperson.column.phonenumber
  description: 
  name: PhoneNumber
  dataType: '[dbo].[Phone]'
  dataTypeRef:
    name: '[dbo].[Phone]'
    id: userdefineddatatype.dbo.phone
    type: UserDefinedDataTypeRef
  maxLengthBytes: 25
  precision: 0
  scale: 0
  isNullable: true
  isComputed: false
  computedText: ''
  isIdentity: false
  identityIncrement: 0
  identitySeed: 0
  inPrimaryKey: false
  isForeignKey: false
  foreignKeys: []
  default: 
  collation: SQL_Latin1_General_CP1_CI_AS
  isFileStream: false
  isFullTextIndexed: false
  databaseId: database.adventureworks2022
  script: ""
- type: ViewColumn
  id: view.sales.vsalesperson.column.phonenumbertype
  description: 
  name: PhoneNumberType
  dataType: '[dbo].[Name]'
  dataTypeRef:
    name: '[dbo].[Name]'
    id: userdefineddatatype.dbo.name
    type: UserDefinedDataTypeRef
  maxLengthBytes: 50
  precision: 0
  scale: 0
  isNullable: true
  isComputed: false
  computedText: ''
  isIdentity: false
  identityIncrement: 0
  identitySeed: 0
  inPrimaryKey: false
  isForeignKey: false
  foreignKeys: []
  default: 
  collation: SQL_Latin1_General_CP1_CI_AS
  isFileStream: false
  isFullTextIndexed: false
  databaseId: database.adventureworks2022
  script: ""
- type: ViewColumn
  id: view.sales.vsalesperson.column.emailaddress
  description: 
  name: EmailAddress
  dataType: NVARCHAR(50)
  dataTypeRef: 
  maxLengthBytes: 50
  precision: 0
  scale: 0
  isNullable: true
  isComputed: false
  computedText: ''
  isIdentity: false
  identityIncrement: 0
  identitySeed: 0
  inPrimaryKey: false
  isForeignKey: false
  foreignKeys: []
  default: 
  collation: SQL_Latin1_General_CP1_CI_AS
  isFileStream: false
  isFullTextIndexed: false
  databaseId: database.adventureworks2022
  script: ""
- type: ViewColumn
  id: view.sales.vsalesperson.column.emailpromotion
  description: 
  name: EmailPromotion
  dataType: INT
  dataTypeRef: 
  maxLengthBytes: 4
  precision: 10
  scale: 0
  isNullable: false
  isComputed: false
  computedText: ''
  isIdentity: false
  identityIncrement: 0
  identitySeed: 0
  inPrimaryKey: false
  isForeignKey: false
  foreignKeys: []
  default: 
  collation: ''
  isFileStream: false
  isFullTextIndexed: false
  databaseId: database.adventureworks2022
  script: ""
- type: ViewColumn
  id: view.sales.vsalesperson.column.addressline1
  description: 
  name: AddressLine1
  dataType: NVARCHAR(60)
  dataTypeRef: 
  maxLengthBytes: 60
  precision: 0
  scale: 0
  isNullable: false
  isComputed: false
  computedText: ''
  isIdentity: false
  identityIncrement: 0
  identitySeed: 0
  inPrimaryKey: false
  isForeignKey: false
  foreignKeys: []
  default: 
  collation: SQL_Latin1_General_CP1_CI_AS
  isFileStream: false
  isFullTextIndexed: false
  databaseId: database.adventureworks2022
  script: ""
- type: ViewColumn
  id: view.sales.vsalesperson.column.addressline2
  description: 
  name: AddressLine2
  dataType: NVARCHAR(60)
  dataTypeRef: 
  maxLengthBytes: 60
  precision: 0
  scale: 0
  isNullable: true
  isComputed: false
  computedText: ''
  isIdentity: false
  identityIncrement: 0
  identitySeed: 0
  inPrimaryKey: false
  isForeignKey: false
  foreignKeys: []
  default: 
  collation: SQL_Latin1_General_CP1_CI_AS
  isFileStream: false
  isFullTextIndexed: false
  databaseId: database.adventureworks2022
  script: ""
- type: ViewColumn
  id: view.sales.vsalesperson.column.city
  description: 
  name: City
  dataType: NVARCHAR(30)
  dataTypeRef: 
  maxLengthBytes: 30
  precision: 0
  scale: 0
  isNullable: false
  isComputed: false
  computedText: ''
  isIdentity: false
  identityIncrement: 0
  identitySeed: 0
  inPrimaryKey: false
  isForeignKey: false
  foreignKeys: []
  default: 
  collation: SQL_Latin1_General_CP1_CI_AS
  isFileStream: false
  isFullTextIndexed: false
  databaseId: database.adventureworks2022
  script: ""
- type: ViewColumn
  id: view.sales.vsalesperson.column.stateprovincename
  description: 
  name: StateProvinceName
  dataType: '[dbo].[Name]'
  dataTypeRef:
    name: '[dbo].[Name]'
    id: userdefineddatatype.dbo.name
    type: UserDefinedDataTypeRef
  maxLengthBytes: 50
  precision: 0
  scale: 0
  isNullable: false
  isComputed: false
  computedText: ''
  isIdentity: false
  identityIncrement: 0
  identitySeed: 0
  inPrimaryKey: false
  isForeignKey: false
  foreignKeys: []
  default: 
  collation: SQL_Latin1_General_CP1_CI_AS
  isFileStream: false
  isFullTextIndexed: false
  databaseId: database.adventureworks2022
  script: ""
- type: ViewColumn
  id: view.sales.vsalesperson.column.postalcode
  description: 
  name: PostalCode
  dataType: NVARCHAR(15)
  dataTypeRef: 
  maxLengthBytes: 15
  precision: 0
  scale: 0
  isNullable: false
  isComputed: false
  computedText: ''
  isIdentity: false
  identityIncrement: 0
  identitySeed: 0
  inPrimaryKey: false
  isForeignKey: false
  foreignKeys: []
  default: 
  collation: SQL_Latin1_General_CP1_CI_AS
  isFileStream: false
  isFullTextIndexed: false
  databaseId: database.adventureworks2022
  script: ""
- type: ViewColumn
  id: view.sales.vsalesperson.column.countryregionname
  description: 
  name: CountryRegionName
  dataType: '[dbo].[Name]'
  dataTypeRef:
    name: '[dbo].[Name]'
    id: userdefineddatatype.dbo.name
    type: UserDefinedDataTypeRef
  maxLengthBytes: 50
  precision: 0
  scale: 0
  isNullable: false
  isComputed: false
  computedText: ''
  isIdentity: false
  identityIncrement: 0
  identitySeed: 0
  inPrimaryKey: false
  isForeignKey: false
  foreignKeys: []
  default: 
  collation: SQL_Latin1_General_CP1_CI_AS
  isFileStream: false
  isFullTextIndexed: false
  databaseId: database.adventureworks2022
  script: ""
- type: ViewColumn
  id: view.sales.vsalesperson.column.territoryname
  description: 
  name: TerritoryName
  dataType: '[dbo].[Name]'
  dataTypeRef:
    name: '[dbo].[Name]'
    id: userdefineddatatype.dbo.name
    type: UserDefinedDataTypeRef
  maxLengthBytes: 50
  precision: 0
  scale: 0
  isNullable: true
  isComputed: false
  computedText: ''
  isIdentity: false
  identityIncrement: 0
  identitySeed: 0
  inPrimaryKey: false
  isForeignKey: false
  foreignKeys: []
  default: 
  collation: SQL_Latin1_General_CP1_CI_AS
  isFileStream: false
  isFullTextIndexed: false
  databaseId: database.adventureworks2022
  script: ""
- type: ViewColumn
  id: view.sales.vsalesperson.column.territorygroup
  description: 
  name: TerritoryGroup
  dataType: NVARCHAR(50)
  dataTypeRef: 
  maxLengthBytes: 50
  precision: 0
  scale: 0
  isNullable: true
  isComputed: false
  computedText: ''
  isIdentity: false
  identityIncrement: 0
  identitySeed: 0
  inPrimaryKey: false
  isForeignKey: false
  foreignKeys: []
  default: 
  collation: SQL_Latin1_General_CP1_CI_AS
  isFileStream: false
  isFullTextIndexed: false
  databaseId: database.adventureworks2022
  script: ""
- type: ViewColumn
  id: view.sales.vsalesperson.column.salesquota
  description: 
  name: SalesQuota
  dataType: MONEY
  dataTypeRef: 
  maxLengthBytes: 8
  precision: 19
  scale: 4
  isNullable: true
  isComputed: false
  computedText: ''
  isIdentity: false
  identityIncrement: 0
  identitySeed: 0
  inPrimaryKey: false
  isForeignKey: false
  foreignKeys: []
  default: 
  collation: ''
  isFileStream: false
  isFullTextIndexed: false
  databaseId: database.adventureworks2022
  script: ""
- type: ViewColumn
  id: view.sales.vsalesperson.column.salesytd
  description: 
  name: SalesYTD
  dataType: MONEY
  dataTypeRef: 
  maxLengthBytes: 8
  precision: 19
  scale: 4
  isNullable: false
  isComputed: false
  computedText: ''
  isIdentity: false
  identityIncrement: 0
  identitySeed: 0
  inPrimaryKey: false
  isForeignKey: false
  foreignKeys: []
  default: 
  collation: ''
  isFileStream: false
  isFullTextIndexed: false
  databaseId: database.adventureworks2022
  script: ""
- type: ViewColumn
  id: view.sales.vsalesperson.column.saleslastyear
  description: 
  name: SalesLastYear
  dataType: MONEY
  dataTypeRef: 
  maxLengthBytes: 8
  precision: 19
  scale: 4
  isNullable: false
  isComputed: false
  computedText: ''
  isIdentity: false
  identityIncrement: 0
  identitySeed: 0
  inPrimaryKey: false
  isForeignKey: false
  foreignKeys: []
  default: 
  collation: ''
  isFileStream: false
  isFullTextIndexed: false
  databaseId: database.adventureworks2022
  script: ""
databaseId: database.adventureworks2022
script: |+
  SET ANSI_NULLS ON
  GO

  SET QUOTED_IDENTIFIER ON
  GO

  CREATE VIEW [Sales].[vSalesPerson]
  AS
  SELECT
      s.[BusinessEntityID]
      ,p.[Title]
      ,p.[FirstName]
      ,p.[MiddleName]
      ,p.[LastName]
      ,p.[Suffix]
      ,e.[JobTitle]
      ,pp.[PhoneNumber]
  	,pnt.[Name] AS [PhoneNumberType]
      ,ea.[EmailAddress]
      ,p.[EmailPromotion]
      ,a.[AddressLine1]
      ,a.[AddressLine2]
      ,a.[City]
      ,[StateProvinceName] = sp.[Name]
      ,a.[PostalCode]
      ,[CountryRegionName] = cr.[Name]
      ,[TerritoryName] = st.[Name]
      ,[TerritoryGroup] = st.[Group]
      ,s.[SalesQuota]
      ,s.[SalesYTD]
      ,s.[SalesLastYear]
  FROM [Sales].[SalesPerson] s
      INNER JOIN [HumanResources].[Employee] e
      ON e.[BusinessEntityID] = s.[BusinessEntityID]
  	INNER JOIN [Person].[Person] p
  	ON p.[BusinessEntityID] = s.[BusinessEntityID]
      INNER JOIN [Person].[BusinessEntityAddress] bea
      ON bea.[BusinessEntityID] = s.[BusinessEntityID]
      INNER JOIN [Person].[Address] a
      ON a.[AddressID] = bea.[AddressID]
      INNER JOIN [Person].[StateProvince] sp
      ON sp.[StateProvinceID] = a.[StateProvinceID]
      INNER JOIN [Person].[CountryRegion] cr
      ON cr.[CountryRegionCode] = sp.[CountryRegionCode]
      LEFT OUTER JOIN [Sales].[SalesTerritory] st
      ON st.[TerritoryID] = s.[TerritoryID]
  	LEFT OUTER JOIN [Person].[EmailAddress] ea
  	ON ea.[BusinessEntityID] = p.[BusinessEntityID]
  	LEFT OUTER JOIN [Person].[PersonPhone] pp
  	ON pp.[BusinessEntityID] = p.[BusinessEntityID]
  	LEFT OUTER JOIN [Person].[PhoneNumberType] pnt
  	ON pnt.[PhoneNumberTypeID] = pp.[PhoneNumberTypeID];

  GO

